### ISSUE TITLE
[BUG] REST APIs return incorrect HTTP Status Codes

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/ml-commons#1076]
**What is the bug?**

1. When a non-existent model ID or ML resource is sent in a REST Request, 400 Bad Request or 500 Internal Server Error or 200 OK are returned.  The return value should be 404 Not Found.

API | HTTP Status Code
-- | --
Update Group | 500
Delete Group | 200
Deploy Model | 500
Get Model | 400
Predict Model | 400
Unload Model | 500
Delete Model | 400
Get Task | 500

**How can one reproduce the bug?**

Use the above APIs with a non-existent Model name or ML Resource.

For Unload model, attempt to unload a model in the deploying state.

**What is the expected behavior?**

Requests that specify a resource that could not be found should return 404 Not Found.

Status code 500 Internal Server Errors should not be returned during expected operation of the application and be reserved for unhandled and unexpected exceptions.

**Do you have any additional context?**

```
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 273

{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Failed to find model to delete with the provided model id: NotAModel"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Failed to find model to delete with the provided model id: NotAModel"
    },
    "status": 400
}
```
```
HTTP/1.1 500 Internal Server Error
content-type: application/json; charset=UTF-8
content-length: 185

{
    "error": {
        "root_cause": [
            {
                "type": "m_l_resource_not_found_exception",
                "reason": "Fail to find model"
            }
        ],
        "type": "m_l_resource_not_found_exception",
        "reason": "Fail to find model"
    },
    "status": 500
}
```

```
HTTP/1.1 500 Internal Server Error
content-type: application/json; charset=UTF-8
content-length: 287

{
    "error": {
        "root_cause": [
            {
                "type": "exception",
                "reason": "Model cannot be deleted in deploying or deployed state. Try undeploy model first then delete"
            }
        ],
        "type": "exception",
        "reason": "Model cannot be deleted in deploying or deployed state. Try undeploy model first then delete"
    },
    "status": 500
}
```

**Comment by Zhangxunmt** [comment]
What is the correct exception name for the 404 in OpenSearch? Do you have an example? @dbwiddis

**Comment by dbwiddis** [comment]
This looks like the source of the bug:
https://github.com/opensearch-project/ml-commons/blob/0e834a87fbef4888ffa03c2b990314e0561c7f50/plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java#L74

It returns on IllegalArgumentException || MLResourceNotFoundException

**Comment by Zhangxunmt** [comment]
https://github.com/opensearch-project/ml-commons/pull/1074. This issue is partially resolved in the pen tests.

**Comment by Zhangxunmt** [comment]
https://github.com/opensearch-project/ml-commons/pull/1079/files

**Comment by Zhangxunmt** [comment]
This issue is fixed with the above 2 PRs.
