### ISSUE TITLE
[FEATURE] Add rate limiter to limit model usage

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#1153]
Most model service provider provide throttling. For now, we don't have rate limiting in ml-commons. That may trigger throttling if user don't control the rate. 

Update: 
Phase1 already released in 2.13 which support throwing error when throttle limit exceeds.
Phase2 we plan to control the rate to not exceed remote model service throttle limit.

**Comment by ylwu-amzn** [comment]
Rate limit on what level: user level, model level , any other ?

**Comment by austintlee** [comment]
Agent level.

**Comment by ylwu-amzn** [comment]
I think we need doc for this feature. Created one doc issue https://github.com/opensearch-project/documentation-website/issues/5839

**Comment by ylwu-amzn** [comment]
Control model enabled or not, if not enabled, user can't run predict for this model 
```
PUT /_plugins/_ml/models/<MODEL_ID>
{"is_enabled": false}
```
Set the throttling parameters to make it allow one request for every 5 second
```
PUT /_plugins/_ml/models/<MODEL_ID>
{
    "rate_limiter": {
        "limit": "2",
        "unit": "MINUTES"
    }
}
```

Create some user level throttler for a specific model
```
POST _plugins/_ml/controllers/<MODEL_ID>
{
  "user_rate_limiter": {
    "user1": {
      "limit": 3,
      "unit": "MINUTES"
    },
    "user2": {
      "limit": 4,
      "unit": "MINUTES"
    }
  }
}
```

**Comment by ylwu-amzn** [comment]
Question from @austintlee on community meeting
> Will it auto scale for adding new node to cluster?

**Comment by saratvemulapalli** [comment]
To add on: how does scale down cluster also work ?

**Comment by ylwu-amzn** [comment]
We are not going to support auto scale and role based throttling.
For scale case, use need to call update API to reapply the throttling to cluster.
