### ISSUE TITLE
[BUG] SQL Plugin bump version failed 2.10

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/ml-commons#1154]
Could not resolve org.opensearch:opensearch-ml-client:2.10.0.0-SNAPSHOT. https://github.com/opensearch-project/sql/actions/runs/5549059306/job/15208455380?pr=1868

**Comment by ylwu-amzn** [comment]
Version bumped in this PR https://github.com/opensearch-project/ml-commons/pull/1157
