### ISSUE TITLE
[BUG] Models groups get auto deleted

### ISSUE THREAD

**Issue by ps48** [opensearch-project/ml-commons#1156]
**What is the bug?**
When a model for remote endpoint is deleted, the model group associated with it gets auto deleted. 

**How can one reproduce the bug?**
1. Create a connector
2. Create a model group 
3. Create a model
4. Delete the model 
5. Check the model group status

**What is the expected behavior?**
Expected behavior is model groups do not get deleted when an associated model is deleted. 

**What is your host/environment?**
 - OS: Ubuntu 22.04
 - Version 2.9
 - Plugins ml-commons

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by rbhavna** [comment]
Hi @ps48 It is the expected behaviour actually. Model group does not serve any purpose when it is empty by itself. So it gets deleted when the last version of it is deleted. Model group gets auto created with the first version and gets auto deleted with the last version.

**Comment by ps48** [comment]
It is okay, if this is an expected behavior. But from a user's point of view, if I create a model group explicitly I may use it in future with other models.

**Comment by rbhavna** [comment]
Yeah makes sense. But the idea here is to maintain consistency with the front-end UI where user does now know about model group explicitly. They provide the access control data with the first model version itself. So for now through APIs, we let user create access control data either with model group or with first version but later switch to only having model version. We first want users to get used to the concept of grouping and access control and once we have front-end ready, we might probably not have creating model group separately.

**Comment by ps48** [comment]
Yes, I agree a UI would be really helpful here. As an end user, I would like to see the access control on each on the models in the UI. Thanks for clarifying the design philosophy here. I'll close this issue for now. 

Linking the documentation here: https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/
