### ISSUE TITLE
[BUG] Handle escaping string parameters explicitly 

### ISSUE THREAD

**Issue by ps48** [opensearch-project/ml-commons#1159]
**What is the bug?**
As of now users are expected to escape special characters, when calling a remote endpoint with the string parameter. This is an additional overhead and is not supported by libraries/languages. In case of TS/JS we use `JSON.stringify` and remove the end quotes and the field name. Manually doing this with/wo regex can create problems in future.

**How can one reproduce the bug?**
1. Register a model with string parameter
2. Make a call to the remote endpoint with normal string
```
POST /_plugins/_ml/models/<model_id>/_predict
{
    "parameters": {
        "prompt": "User: hello \n System:",
        "max_tokens_to_sample": 4848,
        "temperature": 0.001
    }
}

---> Returns error
```
3. Make a call to the remote endpoint with escaped string
```
POST /_plugins/_ml/models/<model_id>/_predict
{
    "parameters": {
        "prompt": "User: hello \\n System:",
        "max_tokens_to_sample": 4848,
        "temperature": 0.001
    }
}

---> Works as expected
```

**What is the expected behavior?**
The expected behavior is this is handled internally by ML Commons to explicitly escape strin. 

**What is your host/environment?**
 - OS: [e.g. iOS] Ubuntu 
 - Version [e.g. 22] 22.04
 - Plugins ML Commons

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ylwu-amzn** [comment]
Thanks for reporting this bug. This fixed in PR #1174
