### ISSUE TITLE
[FEATURE] Eventually Enriched Data - ingest pipeline circuit breakers and asynchronous ingest pipelines

### ISSUE THREAD

**Issue by hijakk** [opensearch-project/ml-commons#1162]
### **Problem definition**
Ingest pipelines supporting both locally hosted and remotely deployed models as discussed [here](https://github.com/opensearch-project/ml-commons/blob/2.x/docs/tutorials/remote_inference.md ) are relatively new Opensearch features and provide flexibility in hooking in resource intensive processes and/or remotely available processes. From what I can tell, these are all intended to be synchronous processes - a record that's intended to go through an ingest pipeline must go through the ingest pipeline before it is exposed. 

As these are resources intensive processes, either for local compute or making remote calls, there's a risk of the data ingest process being significantly disrupted by unexpected spikes in volume, or remote services being unreachable.

From a data engineering/ETL standpoint, this is a double edged sword - while it's very nice for Opensearch to support a larger range of resource intensive data transformations natively, off normal use cases could result in data loss or delays as upstream ETL processes attempt to insert more data into Opensearch through particular pipelines than is possible.

### **Solution**
I propose a two part solution to this:

1. Ingest pipeline circuit breakers - if the remote service starts throwing errors, or rate exceeds some limit, or the number of records waiting to be ingested exceeds specific limits for too long, then fall back to a secondary ingest pipeline logic and make sure the data is exposed quickly
2. Asynchronous ingest pipeline application - allow application of ingest pipeline logic to already indexed data

When it comes to, say, text vectorization, it's certainly valuable to have it done, but the velocity of data can vary significantly. 
Specifically for the case of the ml-commons plugin and neural search, if my ml node can only practically support processing 30 records per second and I get a burst of data at an effective rate of 400 records per second, rather than delaying the ingest of records, it would be great to define a policy saying "if ML node resource consumption is above 80% for more than 60 seconds, fall back to an ingest pipeline that doesn't depend on the ML node". 

Then, another task can be set up to automatically look at all indices matching index pattern names X/Y/Z and apply a specified ingest pipeline to all records matching specific search criteria like "for all records in index abc123, if field xVector doesn't exist, create it according to ingest pipeline 'vectorize-my-stuff', don't exceed processing 10 records per second"

This mitigates the risks of having data stuck in transit due to resource exhaustion or ingest pipeline failure, and allows the application or reapplication of ingest pipelines to already indexed data at "safe" rates.

### **Other alternatives**
Other approaches would seem to come down to a bunch of scripting in the ETL process, handling of edge cases, robust queue systems, etc. This can be a non-trivial task depending on data and ETL process complexity.

**Comment by ylwu-amzn** [comment]
Thanks @hijakk , I think both are valid and good suggestions.

For the first solution, I think it's reasonable to build some circuit breaker or rate limiting (Refer to this issue https://github.com/opensearch-project/ml-commons/issues/1153), 
For 
>  then fall back to a secondary ingest pipeline logic and make sure the data is exposed quickly

Is the "secondary ingest pipeline" a vanilla pipeline which doesn't run ML model, right?

**Comment by jharrisonpnnl** [comment]
@ylwu-amzn - I could see going in one of two directions:

1. Allow users to specify a fallback ingest pipeline. From a best practice perspective, it's suggested that this be a much simpler pipeline than one leveraging ML, since if you're falling back your resource consumption is already high on your cluster. I don't think the "simplicity" can or should be enforced, though, as there easily could be some edge cases where a very fast/lightweight ML model could run in the secondary pipeline instead of a heavier duty primary pipeline ML model. Also likely difficult to enforce "simplicity" as everyone is likely to have a different idea of what that means for their dataflow.
2. Fall back to ingesting with no ingest pipeline at all. This enforces "simplicity", but there could be process risks here for users, especially if their ingest pipeline is dropping or hashing sensitive fields in addition to other work. This could be a viable MVP step towards the full capability, in which case it would need to be clear to users that if they're using this functionality they need to be sure that no unexpected data will get exposed if falling back to no ingest pipeline.

**Comment by hijakk** [comment]
@ylwu-amzn - I could see going in one of two directions:

    Allow users to specify a fallback ingest pipeline. From a best practice perspective, it's suggested that this be a much simpler pipeline than one leveraging ML, since if you're falling back your resource consumption is already high on your cluster. I don't think the "simplicity" can or should be enforced, though, as there easily could be some edge cases where a very fast/lightweight ML model could run in the secondary pipeline instead of a heavier duty primary pipeline ML model. Also likely difficult to enforce "simplicity" as everyone is likely to have a different idea of what that means for their dataflow.
    Fall back to ingesting with no ingest pipeline at all. This enforces "simplicity", but there could be process risks here for users, especially if their ingest pipeline is dropping or hashing sensitive fields in addition to other work. This could be a viable MVP step towards the full capability, in which case it would need to be clear to users that if they're using this functionality they need to be sure that no unexpected data will get exposed if falling back to no ingest pipeline.

**Comment by ylwu-amzn** [comment]
I think both direction are valid. 

For first one, if user need to process the data before ingestion first then invoke ML, maybe a simpler pipeline removing ML part could be a fallback.  If user just invoke ML in the ingest pipeline, then it falls to the second direction, user won't need to have a fallback pipeline.

**Comment by navneet1v** [comment]
@hijakk Thanks for providing this amazing ideas. I really like those ideas. But the ideas that are being proposed will require changes in the OpenSearch Core. Neural Search plugin is just using an extension point to let OpenSearch know that there is this TextEmbedding Processor and what is the definition. All other control when to invoke the processor and when not to, is being done via OpenSearch core. 

@ylwu-amzn I would recommend moving this issue to OpenSearch core as a feature request, where we are looking for 2 types of features:
1. How to make OpenSearch not to use ingest pipeline if cluster is under load.
2. Having async ingest pipeline execution. 

@hijakk These are very great features which you have suggested. I think many other processors can take advantage of this. 

@nknize what your thought?

**Comment by ylwu-amzn** [comment]
@navneet1v Agree, moving to OpenSearch core looks can benefit more. Will wait for suggestions from @nknize and @dblock

**Comment by hijakk** [comment]
Agreed, doesn't need to be tied to ml-commons by any means. Y'all can
replicate on OpenSearch core however you'd like, or if you'd like me to
push it over there at some point that's fine too.

**Comment by navneet1v** [comment]
@hijakk I don't have permission to transfer the issue to core.

@ylwu-amzn see if you have permission. If we all have no permission then @hijakk can copy the contents and create a issue in core only.

**Comment by ylwu-amzn** [comment]
@navneet1v , Sorry to reply late, missed this thread, seem I don't have permission to transfer to core/

@hijakk can you help?

**Comment by hijakk** [comment]
I have created two issues to split the components out in discussion on the main/core OpenSearch project, https://github.com/opensearch-project/OpenSearch/issues/9591 and https://github.com/opensearch-project/OpenSearch/issues/9590 
I think this is probably closable, feel free to reopen if needed?
