### ISSUE TITLE
[UX] Edit forecast

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/ml-commons#1169]
[[UX META] OpenSearch Dashboards Forecasting Dev Ops Metrics](https://github.com/opensearch-project/ux/issues/70)
[[Proposal] Forecasting Dev Ops Metrics and Financial/Inventory Metrics](https://github.com/opensearch-project/ml-commons/issues/408)

**What solution would you like?**

* Forecast page serves both view and edit experiences. The layout is organized by using Described form groups in read-only or editable states respectively. 
* User can view and edit forecast configuration in “Configuration” tab that includes data source details and model parameters. User can view and edit forecast name, description and storage options in “Details” tab. 
* To turn the form into editable state user selects “Edit” in the top right corner of the tab content. 
* To be able to edit forecast in one of the states that are updating on every interval to produce a new datapoint or perform a check for the new data (“Running”, “Initializing test”, “Initializing forecast”, “Awaiting data to initialize forecast”, “Awaiting data to restart forecast”) user will stop or cancel forecast beforehand. Stopping forecast or cancelling awaiting data will transition the forecast into “Inactive” state.
* If user selects “Cancel” to discard the changes or exit the edit mode, the forecast needs to be restarted (By selecting “Test” or “Start forecast”) to go into its initial state. 
* Changing forecast configuration will regenerate the visualization. This will not allow to display previously stored historical forecasts on the visualizations. User needs to be aware of this potential change while selecting to edit a forecast in “Awaiting data to restart” or “Running state”. 
* User might attempt a conflicting action while editing the forecast (examples: selecting an action from the header, navigating away from the page). In this cases a conflicting action modal will be displayed.

**Screen 3.9:** Stop forecast to edit modal dialog
<img width="682" alt="Screenshot 2023-07-29 at 6 56 58 PM" src="https://github.com/opensearch-project/ml-commons/assets/105245012/7415fdd2-f964-45e9-bef5-b04f95d962e8">

#### Stop/Cancel to edit modal dialog messaging

State | Modal header | Callout | Message | CTAs
-- | -- | -- | -- | --
Initializing test - both tabs | Cancel initializing the test to edit? | - | You must cancel initializing the test before editing its configuration. After making change to the forecast, restart the forecast. | <ul><li> Cancel and edit (primary)</li><li>Cancel</li></ul>
Initializing forecast - both tabs | Cancel initializing the forecast to edit? | - | You must cancel initializing the forecast before editing its configuration. After making change to the forecast, restart the forecast. | <ul><li> Cancel and edit (primary)</li><li>Cancel</li></ul>
Awaiting data to initialize forecast - both tabs | Cancel forecast to edit? | - | You must cancel the forecast before editing its configuration. After making change to the forecast, restart the forecast. | <ul><li> Cancel and edit (primary)</li><li>Cancel</li></ul>
Awaiting data to restart - Configuration tab | Cancel forecast to edit? | Editing forecast will wipe historical visualizationsChanging any of the data source or model parameters affects the forecast results and wipes out any historical forecast visualizations. | You must cancel the forecast before editing its configuration. After making change to the forecast, restart the forecast. | <ul><li> Cancel and edit (primary)</li><li>Cancel</li></ul>
Awaiting data to restart - Details tab | Cancel forecast to edit? | - | You must cancel the forecast before editing its configuration. After making change to the forecast, restart the forecast. | <ul><li> Cancel and edit (primary)</li><li>Cancel</li></ul>
Running - Configuration tab | Stop forecast to edit? | Editing forecast will wipe historical visualizationsChanging any of the data source or model parameters affects the forecast results and wipes out any historical forecast visualizations. | You must stop the forecast before editing its details. After making change to the forecast, restart the forecast. | <ul><li> Stop and edit (primary)</li><li>Cancel</li></ul>
Running - Details tab | Stop forecast to edit? | - | You must stop the forecast before editing its details. After making change to the forecast, restart the forecast. | <ul><li> Stop and edit (primary)</li><li>Cancel</li></ul>

**Screen 3.10:** Configuration tab in read-only mode

<img width="829" alt="Screenshot 2023-07-29 at 7 02 34 PM" src="https://github.com/opensearch-project/ml-commons/assets/105245012/f0517de3-0863-4463-bf6e-701b5f21ab43">

**Screen 3.11:** Configuration tab in editable mode
<img width="732" alt="Screenshot 2023-07-29 at 7 03 37 PM" src="https://github.com/opensearch-project/ml-commons/assets/105245012/52ce77ae-8e7f-400c-8bdf-6c6447a85dd8">

**Screen 3.12:** Details tab in read-only mode
<img width="1068" alt="Screenshot 2023-07-20 at 12 59 50 PM" src="https://github.com/opensearch-project/ml-commons/assets/105245012/f1195155-8e84-4ff3-b3c8-b31c3d1a51a4">

**Screen 3.13:** Details tab in editable mode
<img width="1054" alt="Screenshot 2023-07-20 at 1 06 08 PM" src="https://github.com/opensearch-project/ml-commons/assets/105245012/9e386579-529f-41bd-b18b-377d2c461566">

#### State transitions for editing a forecast

Read-only state | Editable state | Configuration tab bottom bar buttons | Details tab bottom bar buttons
-- | -- | -- | --
Inactive | Inactive | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | Update (primary)Cancel
Inactive:stopped | Inactive:stopped | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Awaiting data to initialize | **Inactive:stopped** | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Awaiting data to restart | **Inactive:stopped** | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Initializing test | **Inactive** | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Initializing forecast | **Inactive** | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Test complete | Test complete | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Running | **Inactive: stopped** | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Initializing forecast failed | Initializing forecast failed | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Forecast failed | Forecast failed | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>
Initializing test failed | Initializing test failed | <ul><li>Update and test (primary)</li><li>Update</li><li>Cancel</li></ul> | <ul><li>Update (primary)</li><li>Cancel</li></ul>

**Screen 3.14:** Conflicting action modal

<img width="478" alt="Screenshot 2023-07-20 at 1 10 30 PM" src="https://github.com/opensearch-project/ml-commons/assets/105245012/ce5a0deb-de88-4ffb-8865-bd2e46253c3a">

### Delete forecast

User can delete a forecast from the Forecasts list view or from a forecast page. When user selects “Delete” button, the system displays the confirmation modal to avoid accidental deletion. For the running state and for initializing test or initializing forecast the confirmation modal contains a callout highlighting the state of the forecast. No cancelling or stopping is required to delete a forecast.

**Screen 3.15:** Delete forecast confirmation modal dialog.
<img width="422" alt="Screenshot 2023-07-25 at 4 47 11 PM" src="https://github.com/opensearch-project/ml-commons/assets/105245012/61219556-d906-4968-b46f-0514c26bfc41">

**Comment by xeniatup** [comment]
Replaced with https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/577

**Comment by ylwu-amzn** [comment]
colse this one as it's moved to AD
