### ISSUE TITLE
[Enhancement] Support more Action types in ML Extensibility Framework

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/ml-commons#1230]
Typically Remote model server support multiple APIs like remote inference, healthy check, or training, etc. Currently in Ml-commons we only support the "predict" API which maps to the "remote inference" in the remote model servers. We should add more APIs in Ml-Commons and map the new APIs to invoke remote servers for other actions like "health check", "training", etc.

**Comment by austintlee** [comment]
I'm not familiar with "health check".  Can you give an example?  Maybe using OpenAI or SageMaker?

**Comment by mingshl** [comment]
will have progress when the batch inference project gets in progress

**Comment by Zhangxunmt** [comment]
This is a similar issue with https://github.com/opensearch-project/ml-commons/issues/2488 and https://github.com/opensearch-project/ml-commons/issues/2484. Closing this one as these two new issues have more details.
