### ISSUE TITLE
[FEATURE] ConversationalMemoryClient - different ways to retrieve relevant interactions

### ISSUE THREAD

**Issue by austintlee** [opensearch-project/ml-commons#1284]
**Is your feature request related to a problem?**
As suggested in #1275 by @jngz-es , we want to add more ways to retrieve interactions from conversational memory.

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**
#1150

**Comment by austintlee** [comment]
@jngz-es please feel free to suggest other ways to retrieve interactions.  As of v2.10.0, we only support "lastN".

**Comment by dhrubo-os** [comment]
Closing this Issue after the discussion in the triage meeting.
