### ISSUE TITLE
[FEATURE] Add model level stats

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#1295]
For now the stats API collects data on 3 levels: 
- cluster: like model index status
- node: like how many model deployed on node
- model category: like how many request for text embedding model

For some use case, user may prefer to know the model level stats. For example, user created 2 remote models: one for openAI, one for Cohere. Both model stats data will be aggregated as REMTOE model on stats "model category" level. That's hard to user to tell how many requests sent to openAI or cohere separately.

**Comment by dhrubo-os** [comment]
@ylwu-amzn, I'm closing this issue as this is addressed in [this PR](https://github.com/opensearch-project/ml-commons/pull/1330)
