### ISSUE TITLE
[FEATURE] Examples of ML Remote Models

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/ml-commons#1332]
**Is your feature request related to a problem?**
At the moment we have [blueprints](https://github.com/opensearch-project/ml-commons/tree/2.x/docs/remote_inference_blueprints) for Remote ML model connectors. This allows users to know in a straightforward way how to create connectors. We don't however have samples of how to create models that utilize those connectors at least that I could find. 

The two examples out there are dramatically different and may leave developers confused on how to deploy a model for their remote connector.
 
https://github.com/opensearch-project/ml-commons/blob/f5c20fb31bf80c0cd048b8bceee72ada355f2920/docs/tutorials/remote_inference.md?plain=1#L244C1-L244C31

https://github.com/opensearch-project/documentation-website/blob/b024b6ccc2e81abab6d07771bd145f71c1ada3c3/_ml-commons-plugin/extensibility/connectors.md?plain=1#L80

**What solution would you like?**
We should either have a guide or a set of blueprints ready for new developers to utilize to connect to some of the most common models. I feel like we should consider breaking `docs/remote_inference_blueprints` into a structure more like the following: 

```bash
remote_inference_blueprints
├── open_ai
│   ├── connector_blueprint.md
│   ├── gpt-3.5-model.md
│   └── gpt-4-model.md
├── cohere
└── ...
```

**What alternatives have you considered?**
With excluding these we will cripple the adoption of our ML Framework.

**Do you have any additional context?**
n/a

**Comment by dtaivpp** [comment]
Turns out this was just due to the documentation page referencing the local connector creation settings where it should have a different sample. Getting closed with https://github.com/opensearch-project/documentation-website/pull/5017

**Comment by ylwu-amzn** [comment]
@dtaivpp can we close this issue now?

**Comment by dtaivpp** [comment]
Feel free
