### ISSUE TITLE
[FEATURE] add sparse encoding and tokenizer

### ISSUE THREAD

**Issue by xinyual** [opensearch-project/ml-commons#1339]
**Is your feature request related to a problem?**
Currently, we are trying to add sparse encoding and tokenizer in ml-commons to support sparse neural search used by:https://github.com/opensearch-project/neural-search/issues/230. 

**What solution would you like?**
Both sparse encoding and tokenizer would be model and can be deployed locally, and can predict by calling current API. Both will be related to a function Name and the return would be the token with its weights like
{"hello": 1.0, ....}

**Comment by ylwu-amzn** [comment]
released in 2.11
