### ISSUE TITLE
[FEATURE] Improve Developers Guide

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/ml-commons#1400]
The following two links can be helpful to ramp up with Git. 

https://learngitbranching.js.org/
https://gist.github.com/ashwin-pc/84ee8bd937caecd6a193e2a6a4c4fe34

We have a [section](https://github.com/opensearch-project/ml-commons/blob/main/DEVELOPER_GUIDE.md#install-git) about installing git.

We can include these two links in that section as reference.

**Comment by divitr** [comment]
@dhrubo-os I would like to do this as a first issue

**Comment by dhrubo-os** [comment]
Sure, I assigned the issue to you.
