### ISSUE TITLE
http connector with hugging face, i am not able to create a new connector using blueprint

### ISSUE THREAD

**Issue by ramda1234786** [opensearch-project/ml-commons#1468]
http connector with hugging face, i am not able to create a new connector using blueprint

Currently  ml-commons support only Open AI, Cohere and Sagemaker for LLMs
I am trying to connect with hugging face with http connector but it fails

```
{
  "name": "Hugging Face GPT Connector",
  "description": "The connector to Hugging Face GPT Language Model",
  "version": 1,
  "protocol": "http",
  "parameters": {
    "endpoint": "api-inference.huggingface.co",
    "model": "gpt2",
    "temperature": 1.0
  },
  "actions": [
    {
      "action_type": "predict",
      "method": "POST",
      "url": "${parameters.endpoint}/models/gpt2",
      "request_body": "{ \"inputs\": \"${parameters.inputs}\", \"options\": {\"temperature\": ${parameters.temperature}} }"
    }
  ]
}
```

I get this below error, is there any restriction to use LLM other than those 3 mentioned above?

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Connector URL is not matching the trusted connector endpoint regex, URL is: api-inference.huggingface.co/models/gpt2"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Connector URL is not matching the trusted connector endpoint regex, URL is: api-inference.huggingface.co/models/gpt2"
    },
    "status": 400
}
```

**Comment by austintlee** [comment]
@ramda1234786 Have you done this step - https://opensearch.org/docs/latest/ml-commons-plugin/extensibility/index/#adding-trusted-endpoints.  If so, can we see the trusted endpoints you set up?  You might have made a typo.

**Comment by dhrubo-os** [comment]
If you look at the [connector examples](https://opensearch.org/docs/latest/ml-commons-plugin/extensibility/connectors/), you can see that, value of url is: `"url": "https://${parameters.endpoint}/v1/chat/completions",`. So in the url we need to provide `https://` also.

**Comment by ramda1234786** [comment]
Thanks @dhrubo-os , its working for me now after adding the `https`. So the connector is created, will check how it functions. I am closing this issue as it has been addressed.

**Comment by MiaNCSU** [comment]
Hello, I am attempting to create a rag pipeline for conversational search, using the huggingface model and a modified version of the connector provided above:

```
{
    "name": "sentence-transformers/all-MiniLM-L6-v2",
    "description": "The connector to Hugging Face GPT Language Model",
    "version": "1.0.1",
    "protocol": "http",
    "parameters": {
        "endpoint": "api-inference.huggingface.co",
        "model": "gpt2",
        "temperature": 1.0
    },
    "credential": {
        "HF_key": "<api token>"
    },
    "actions": [
        {
            "action_type": "predict",
            "method": "POST",
            "url": "https://api-inference.huggingface.co/models/sentence-transformers/all-MiniLM-L6-v2",
            "headers": {
                "Authorization": "Bearer ${credential.HF_key}"
            },
            "request_body": """{ 
                "model": "${parameters.model}", 
                "messages": ${parameters.messages},
                "temperature": ${parameters.temperature},
                "inputs" : "${parameters.input}"
            }"""
        }
    ]
}
```

This version correctly includes the endpoint url for HuggingFace's Inference API, includes my access token, and also includes the request body... However, I keep getting unreadable errors that seem to be coming from the HuggingFace side:

```
TransportError(500, 'null_pointer_exception', 'Cannot invoke "java.util.Map.get(Object)" because "error" is null'
```

What should I define parameters.input to be ???

I have successfully registered the model and rag pipeline with opensearch, receiving the message "acknowledged: true". But I am struggling with the HuggingFace connector blueprint. Is there already an established version of this, which I can use for conversational search??? Any help is appreciated, there is not a lot of online documentation for this.
