### ISSUE TITLE
[FEATURE] Support for timeout in http connector

### ISSUE THREAD

**Issue by austintlee** [opensearch-project/ml-commons#1470]
**Is your feature request related to a problem?**
Occasionally, a request to OpenAI just sits for 10 minutes and fails with a "bad gateway" error.

**What solution would you like?**
I would like to specify the maximum amount of time an http connector should wait before it cancels a request.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by ylwu-amzn** [comment]
@zane-neo , Zan, since you built the http client factory, can you give some suggestion/solution for this?

**Comment by ylwu-amzn** [comment]
@zane-neo  as you find other http client perfromance issue, can you create issue for tracking that?

**Comment by zane-neo** [comment]
> @zane-neo , Zan, since you built the http client factory, can you give some suggestion/solution for this?

I think we can let user configure these, including: connection timeout, read timeout, connection pool size etc, I will create a PR to address this.

**Comment by zane-neo** [comment]
> @zane-neo as you find other http client perfromance issue, can you create issue for tracking that?

Found it here: https://github.com/opensearch-project/ml-commons/issues/1537

**Comment by austintlee** [comment]
#1835

**Comment by ylwu-amzn** [comment]
Done in this PR https://github.com/opensearch-project/ml-commons/pull/1835
