### ISSUE TITLE
[FEATURE] add code coverage report for commons and memory modules

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/ml-commons#1542]
**Is your feature request related to a problem?**

Currently in ml-commons we see code coverage for 4 modules but not for other modules: `opensearch-ml-commons` and `opensearch-ml-memory`

We need to add similar like [this](https://github.com/opensearch-project/ml-commons/blob/main/ml-algorithms/build.gradle#L76-L84) in the corresponding build.gradle file for the modules.

**Comment by austintlee** [comment]
https://github.com/opensearch-project/ml-commons/blob/5d9324c8d0e684ab486fc1f530d44a4fffafb1f6/memory/build.gradle#L47-L54

Isn't this it?

**Comment by dhrubo-os** [comment]
I don't see memory module [here](https://app.codecov.io/gh/opensearch-project/ml-commons)

**Comment by dhrubo-os** [comment]
Thanks @TrungBui59 for solving this issue. We can see all the modules of the ml-commons now [here](https://app.codecov.io/gh/opensearch-project/ml-commons).
