### ISSUE TITLE
[FEATURE] Add a trusted connector endpoint via environment or config variable

### ISSUE THREAD

**Issue by binarymax** [opensearch-project/ml-commons#1555]
**Issue: the allow-list for endpoints is hard-coded**
For new connectors that access ML services via REST, the blueprint requires the URL to match a trusted list of endpoints, which are explicitly listed here: https://github.com/opensearch-project/ml-commons/blob/8c3e453a7c3eba68135bf503531d909a12db7537/plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java#L127 

```
                .of(
                    "^https://runtime\\.sagemaker\\..*[a-z0-9-]\\.amazonaws\\.com/.*$",
                    "^https://api\\.openai\\.com/.*$",
                    "^https://api\\.cohere\\.ai/.*$"
                ),
```

This prevents other ML REST service endpoints from being added.

**What solution would you like?**
Since trust must be maintained by the server operator, I propose allowing an environment or configuration variable to allow an  additional endpoint.  For example:

```bash
OPENSEARCH_ML_COMMONS_TRUSTED_ENDPOINT="^https://example\\.com/.*$"
```

```yaml
opensearch.ml.commons.trusted_endpoint: "^https://example\\.com/.*$"
```

**Comment by binarymax** [comment]
Note:  for consistency, I will use the yml approach unless there are objections.

**Comment by austintlee** [comment]
You can update this via a REST call:

https://opensearch.org/docs/latest/ml-commons-plugin/extensibility/index/#adding-trusted-endpoints

**Comment by binarymax** [comment]
Oh I hadn't seen that!  Closing this issue.  Thanks!
