### ISSUE TITLE
[FEATURE] Tool development for NeuralSparse Tool

### ISSUE THREAD

**Issue by zhichao-aws** [opensearch-project/ml-commons#1675]
**Is your feature request related to a problem?**
Agent framework (https://github.com/opensearch-project/ml-commons/issues/1161 ) needs tools to extend functionality. This issue propose to add NeuralSparse tool to it.

**What solution would you like?**
Build a tool to support neural_sparse query. The interface should be similar to VectorDB tool. Since this tool is very similar to VectorDB tool, we can create an abstract retriever tool class and make the 2 tools extend it.
 
**What alternatives have you considered?**
N/A.

**Do you have any additional context?**
#1161 #1546

**Comment by zhichao-aws** [comment]
Please assign this issue to me

**Comment by dhrubo-os** [comment]
I just assigned the issue to you. Thanks for working on this.
