### ISSUE TITLE
[FEATURE] Add ML-Commons Tutorials / Documentation

### ISSUE THREAD

**Issue by Arnav-Gr0ver** [opensearch-project/ml-commons#1683]
**Is your feature request related to a problem?**
Docs contains few tutorials on ML-Commons Plugin features, e.g. remote connector, neural-search 

**What solution would you like?**
Write documentation for ML-Commons features in Docs

**What alternatives have you considered?**
OpenSearch Blog, Docs

**Do you have any additional context?**

**Comment by ylwu-amzn** [comment]
We have built tutorials: https://github.com/opensearch-project/ml-commons/tree/2.x/docs/tutorials
Will close this issue. Feel free to cut new issue if need more tutorials.
