### ISSUE TITLE
[BUG] LLM returns action that doesn't match any of the tool's name

### ISSUE THREAD

**Issue by xluo-aws** [opensearch-project/ml-commons#1735]
**What is the bug?**
Although the prompt tells LLM to use one of the tool's name configured in agent as action, LLM may still return an action that doesn't match any of the tool's name

**How can one reproduce the bug?**
1. Config a conversational agent with visualization tool and cat index tool
2. Open a new chatbot conversation
3. Ask "How many indexes in my cluster", chatbot should return the right answer
4. In the same conversation ask "How to split an index"
5. You may either get an empty response or the right answer. But if you click how was it generated, you'll find the last step will have Output as "no access to this tool".  

**What is the expected behavior?**
A few sentences to describe how to split an index

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/ml-commons/assets/109580118/63434742-3c8a-433d-ae97-25c1e748749c)

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dhrubo-os** [comment]
Thanks @xluo-aws , just assigned this to you.

**Comment by Hailong-am** [comment]
Have some update in https://github.com/opensearch-project/ml-commons/pull/1751
