### ISSUE TITLE
Machine Learning Dashboard shows partially response after restarting non-ml nodes

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/ml-commons#1774]
**What is the bug?**
Machine Learning Dashboard shows partially response after restarting non-ml nodes, more details can be found here: https://forum.opensearch.org/t/model-is-partially-responding-in-case-of-non-ml-node-restart/17030

**How can one reproduce the bug?**
1. Setup a cluster with 2.11.x version with data nodes and ml nodes.
2. Register a local model and deploy the model.
3. restart a data node and invoke profile API: /_plugins/_ml/profile/models/<your_model_id>?view=model
4. Check the `target_worker_nodes` and `worker_nodes`, you can see the difference.

**What is the expected behavior?**
`target_worker_nodes` and `worker_nodes` should be same.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dhrubo-os** [comment]
resolving this issue in respect of https://github.com/opensearch-project/ml-commons/pull/1775
