### ISSUE TITLE
[BUG] When Hitting ML Connector Search Endpoint, returns index not found

### ISSUE THREAD

**Issue by LucasWang750** [opensearch-project/ml-commons#1787]
**What is the bug?**
A clear and concise description of the bug.
When Hitting ML Connector Search Endpoint, returns index not found

**How can one reproduce the bug?**
1.Run POST GET /_plugins/_ml/connectors/_search before connector is created 
2.Returns 404 error :
An error occurred while initializing cluster bootstrap: NotFoundError(404, 'index_not_found_exception', 'no such index [.plugins-ml-connector]', .plugins-ml-connector, index_or_alias)

**What is the expected behavior?**
Return no connectors

**What is your host/environment?**
 - OS: Mac OS X
 - Version: OpenSearch 2.11
 - Plugins

**Comment by Zhangxunmt** [comment]
This behavior is expected because you haven't created a connector yet. The connector index is created when the first connector is created. This is not a service error so the error code 404 is returned. This is like you visiting a web service that hasn't been created yet.

**Comment by ylwu-amzn** [comment]
The error `NotFoundError(404, 'index_not_found_exception', 'no such index [.plugins-ml-connector]', .plugins-ml-connector, index_or_alias)` expose the implementation details and looks confusing to community user. I think we can fine tune the error message to make it easier to understand like "no connector created"

**Comment by ylwu-amzn** [comment]
@samuel-oci will help on this

**Comment by samuel-oci** [comment]
Sure thing @ylwu-amzn feel free to assign it to me.
