### ISSUE TITLE
[BUG]Ingest pipelines using remote models results in failure.

### ISSUE THREAD

**Issue by arjunkumargiri** [opensearch-project/ml-commons#1833]
**What is the bug?**
**Goal:** Create text embedding by making use of remote model.
**Bug:** Document index requests fails though remote model `_predict` requests succeeds.

**How can one reproduce the bug?**
1. Create connector
```
POST _plugins/_ml/connectors/_create

{
    "name": "Sagemaker connector",
    "description": "Sagemaker connector",
    "version": 1,
    "protocol": "aws_sigv4",
    "parameters": {
        "region": "us-east-1",
        "service_name": "sagemaker",
        "endpoint": "sagemaker.us-east-1.amazonaws.com",
        "auth": "Sig_V4",
        "content_type": "application/json"
    },
    "credential": {
        <<credentials>>
    },
    "actions": [
        {
            "action_type": "predict",
            "method": "POST",
            "url": "<<sagemaker endpoint>>",
            "headers": {
                "content-type": "application/json",
                "x-amz-content-sha256": "required"
            },
            "request_body": "{\"inputs\": \"test data\"}"
        }
    ]
}

```
2. Create model
```
POST _plugins/_ml/models/_register?deploy=true
{
    "name": "sagemaker model",
    "function_name": "remote",
    "model_group_id": "<<model_group_id>>",
    "description": "sagemaker model",
    "connector_id": "model_id"
}
```
3. Setup pipeline
```
PUT /_ingest/pipeline/test-pipeline-sagemaker-model
{
  "description": "text embedding pipeline",
  "processors": [
    {
      "text_embedding": {
        "model_id": "<<model_id>>",
        "field_map": {
          "text": "embedding"
        }
      }
    }
  ]
}
```
4. Setup index
```
PUT test_index
{
  "mappings": {
    "properties": {
      "text": {
        "type": "text"
      },
      "embedding": {
        "type": "knn_vector",
        "dimension": 384
      }
    }
  },
  "settings": {
    "index": {
      "knn.space_type": "cosinesimil",
      "default_pipeline": "test-pipeline-sagemaker-model",
      "knn": "true"
    }
  }
}
```

5. Index data
```
POST _bulk
{"index": {"_index": "test_index", "_id": "2"}}
{"text": "test text"}
```

Request fails with error message: 
```
[2024-01-03T17:56:35,399][ERROR][o.o.n.m.MLCommonsClientAccessor] [dev-dsk-arjung-2c-3dee26a3.us-west-2.amazon.com] Received following output tensor from a model, there is no detailed error message: ModelTensor(name=response, data=null, shape=null, dataType=null, byteBuffer=null, result=null, dataAsMap={response=[0.0354621559381485, 0.053523771464824677, -0.04255664721131325, ..., -0.08477019518613815]})
```

However performing predict request directly on the model fails:
```
POST _plugins/_ml/models/pLcB0YwBvWY9YvVZXaT5/_predict
{
  "parameters": {
    "input": "test"
  }
}
```

Response
```
{
  "inference_results": [
    {
      "output": [
        {
          "name": "response",
          "dataAsMap": {
            "vectors": [
              0.0354621559381485,
              0.053523771464824677,
              ....
              -0.08477019518613815
            ]
          }
        }
      ],
      "status_code": 200
    }
  ]
}
```

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by arjunkumargiri** [comment]
Issue seems to be due to the fact that neural search is checking for embedding data to be part of `data` field in `ModelTensor` output but with remote model embedding are available as part of `dataAsMap` field.

https://github.com/opensearch-project/neural-search/blob/2.x/src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java#L194

**Comment by austintlee** [comment]
I think you're missing this?

https://opensearch.org/docs/latest/ml-commons-plugin/remote-models/blueprints/#amazon-sagemaker-default-pre--and-post-processing-functions-for-neural-search

**Comment by Zhangxunmt** [comment]
I think this problem is resolved using the created connector and model through CFN integration.

**Comment by arjunkumargiri** [comment]
> I think you're missing this?
> 
> https://opensearch.org/docs/latest/ml-commons-plugin/remote-models/blueprints/#amazon-sagemaker-default-pre--and-post-processing-functions-for-neural-search

This seems to solve the problem. It might be worth improving exception handling in case of invalid integration between neural search and remote models. Ideally this issue should be caught while setting up ingest pipeline.
