### ISSUE TITLE
[BUG] Remote Connector: Malformed input request - Bedrock Cohere Embed English V3

### ISSUE THREAD

**Issue by ashihCT** [opensearch-project/ml-commons#1836]
**What is the bug?**
Does AWS hosted Opensearch work with Bedrock Cohere Embed English V3? I see you have [blueprints](https://github.com/opensearch-project/ml-commons/blob/2.x/docs/remote_inference_blueprints/cohere_v3_connector_embedding_blueprint.md) for both Bedrock and for Cohere independently. 

I am able to create, register, deploy. 
On prediction I get the following error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "status_exception",
        "reason": "Error from remote service: {\"message\":\"Malformed input request: 2 schema violations found, please reformat your input and try again.\"}"
      }
    ],
    "type": "status_exception",
    "reason": "Error from remote service: {\"message\":\"Malformed input request: 2 schema violations found, please reformat your input and try again.\"}"
  },
  "status": 400
}
```

**How can one reproduce the bug?**

1. Create Remote Model Group
```
POST /_plugins/_ml/model_groups/_register
{
  "name": "remote_model_group",
  "description": "A model group for external models"
}
```

2. Create Remote Connector
```
POST /_plugins/_ml/connectors/_create
{
    "name": "Amazon Bedrock",
    "description": "The connector to the Cohere embedding model",
    "version": 1,
    "protocol": "aws_sigv4",
    "credential": {
        "roleArn": "arn:aws:iam::ACCTNUM:role/role_name"
    },
    "parameters": {
        "region": "us-east-1",
        "service_name": "bedrock"
    },
    "actions": [
        {
            "action_type": "predict",
            "method": "POST",
            "headers": {
                "content-type": "application/json"
            },
            "url": "https://bedrock-runtime.us-east-1.amazonaws.com/model/cohere.embed-english-v3/invoke",
            "request_body": "{ \"texts\": ${parameters.texts}, \"truncate\": \"${parameters.truncate}\", \"model\": \"${parameters.model}\", \"input_type\": \"${parameters.input_type}\" }",
            "pre_process_function": "connector.pre_process.cohere.embedding",
            "post_process_function": "connector.post_process.cohere.embedding"
        }
    ]
}
```

3. Register the Remote Connector
```
POST /_plugins/_ml/models/_register
{
    "name": "bedrock-cohere-embed-english-v3",
    "function_name": "remote",
    "model_group_id": "{GROUP ID from STEP 1}",
    "description": "Cohere EmbedV3",
    "connector_id": "{CONNECTOR ID FROM STEP 2}"
}
```

4. Deploy the Connector:
```
POST /_plugins/_ml/models/{MODEL_ID}/_deploy
```

5. Test the Model
```
POST /_plugins/_ml/models/{MODEL_ID}/_predict
{
  "parameters": {
    "texts": ["Say this is a test"],
    "input_type": "search_document",
    "model": "embed-english-v3.0",
    "truncate": "END"
  }
}
```

**What is the expected behavior?**
Returns a successful response with embedding vectors

**What is your host/environment?**
 - OS: OpenSearch Dev Tools in AWS OpenSearch Managed Cluster
 - Version OpenSearch_2_11_R20231113-P2
 - Plugins - None.

**Do you have any screenshots?**
Dev Tools in OS Dashboard
<img width="627" alt="Screenshot 2024-01-04 at 10 33 23 AM" src="https://github.com/opensearch-project/ml-commons/assets/42871040/da02aebd-fb38-4095-9c4d-ff50123f5aa9">

Machine Learning Tab in OS Dashboard
<img width="1250" alt="Screenshot 2024-01-04 at 10 43 21 AM" src="https://github.com/opensearch-project/ml-commons/assets/42871040/7a7471fc-6df8-49ef-bab5-ce9b289c2771">

**Comment by Zhangxunmt** [comment]
https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-embed.html, Can you pls check the parameters of the cohere models hosted in Bedrock? It may be different than that from the original Cohere model. 
Can you pls try using "NONE" in the truncate value?

Example:
POST _plugins/_ml/models/SReqZYwBIHxKcYgq5ZJE/_predict
{
  "parameters": {
     "texts": ["This is a test document", "This is another document"],
     "input_type": "search_document",
     "truncate": "NONE"
  }
}

**Comment by ashihCT** [comment]
@Zhangxunmt  that did it! Thank you! I had to recreate the connector without the model parameter and change the truncate to "NONE" and it's returning properly. Hope you guys add it to the Blueprints to make it easier for other people :)
