### ISSUE TITLE
[BUG] Invalid JSON in payload error despite sending a valid JSON with all required parameters

### ISSUE THREAD

**Issue by NeuralFlux** [opensearch-project/ml-commons#1872]
**What is the bug?**
Sending a predict request to a model that uses SageMaker connector like so
```
POST /_plugins/_ml/models/_6gdD40BZqSAbrEiV6DT/_predict
{
  "parameters": {
    "inputs": "test sentence"
  }
}
```
produces an error
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Invalid JSON in payload"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Invalid JSON in payload"
  },
  "status": 400
}
```
despite having a _complete_ and _valid_ JSON.

**How can one reproduce the bug?**
1. Setup a connector to a SageMaker endpoint (any endpoint is okay since the error is in the connector itself)
2. Deploy the model and note the model ID
3. Predict `curl -XPOST "http://localhost:9200/_plugins/_ml/models/<Model ID>/_predict" -H 'Content-Type: application/json' -d'
{
  "parameters": {
    "inputs": "test sentence"
  }
}'`

**What is the expected behavior?**
The request should trigger processing of `request_body` in the connector without any errors.

**What is your host/environment?**
 - AWS OpenSearch Service 2.11
 - ML Commons

**Do you have any additional context?**
Passing `"inputs": ["test sentence"]` works. However, I need the embedding on just the sentence without the extra square brackets. Moreover, `${parameters.input}[0]` works without any errors but gave different embedding for a test sentence than what was expected.

**Comment by ramda1234786** [comment]
Hi @NeuralFlux works well for me. May be some problem in request_body while creating connector

It should be

`  "request_body": "{ \"inputs\": \"${parameters.inputs}\" }"`

![image](https://github.com/opensearch-project/ml-commons/assets/147361031/777b51e7-1d9b-4e31-895f-34e6c140e9ff)

**Comment by NeuralFlux** [comment]
It gives me the same error with`"request_body": "\"${parameters.input}\""`. Essentially, is there a way to send a JSON that is only a string? I believe that is a valid JSON too.

Because as I mentioned, the following works for `"request_body": "${parameters.input}"`
```
POST /_plugins/_ml/models/_6gdD40BZqSAbrEiV6DT/_predict
{
  "parameters": {
    "inputs": ["test sentence"]
  }
}
```

**Comment by b4sjoo** [comment]
Hi @NeuralFlux , could you please share your connector configuration?

**Comment by NeuralFlux** [comment]
Sure thing, it's 
```json
"actions": [
      {
         "action_type": "predict",
         "method": "POST",
         "headers": {
            "content-type": "application/x-text"
         },
         "url": "<INFERENCE_ENDPOINT>",
         "request_body": "${parameters.inputs}"
      }
   ]
```
