### ISSUE TITLE
[Enhancement] Refactor Memory APIs to be more generic

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/ml-commons#1875]
Memories are implemented in Ml-Commons with multiple APIs for conversations, interactions, etc. It was designed to support conversational search in the first place. However, the ultimate goal of the memory is to support all applications that require history data. To this end, this issue proposes some refactor to the memory APIs to make them more generic and scalable.

Create Conversation
~~~
Create conversation:
/_plugins/_ml/memory/conversation/_create

Change to

Create conversation:
POST /_plugins/_ml/memory
~~~

Create interaction
~~~
/_plugins/_ml/memory/conversation/{conversation_id}/_create

change to

POST /_plugins/_ml/memory/{memory_id}/messages
~~~

List/Get Conversations
~~~
/_plugins/_ml/memory/conversation/_list

Change to

GET /_plugins/_ml/memory
~~~

List/Get interactions
~~~
/_plugins/_ml/memory/conversation/{conversation_id}/_list

change to

GET /_plugins/_ml/memory/{memory_id}/messages
~~~

List/Get traces
~~~
/_plugins/_ml/memory/trace/{interaction_id}/_list

change to 

GET /_plugins/_ml/memory/message/{message_id}/traces
~~~

Get single conversation and interaction
~~~
get conversation 
/_plugins/_ml/memory/conversation/{conversation_id}

get interaction
/_plugins/_ml/memory/conversation/{conversation_id}/{interaction_id}

Change to 

get conversation 
GET /_plugins/_ml/memory/{memory_id}

get interaction
GET /_plugins/_ml/memory/message/{message_id}
~~~

Update Conversation
~~~
/_plugins/_ml/memory/conversation/{conversation_id}/_update

Change to 

PUT /_plugins/_ml/memory/{memory_id}
~~~

Update Interaction
~~~
/_plugins/_ml/memory/interaction/{interaction_id}/_update

Change to 

PUT /_plugins/_ml/memory/message/{message_id}
~~~

Delete Conversation
~~~
DELETE /_plugins/_ml/memory/conversation/{conversation_id}/_delete

Change to 

DELETE /_plugins/_ml/memory/{memory_id}
~~~

Search Conversation
~~~
/_plugins/_ml/memory/conversation/_search

Change to 

GET/POST /_plugins/_ml/memory/_search
~~~

Search Interactions
~~~
/_plugins/_ml/memory/conversation/{conversation_id}/_search

Change to 

GET/POST /_plugins/_ml/memory/{memory_id}/_search
~~~

**Comment by Zhangxunmt** [comment]
@HenryL27 @austintlee Can you please review these APIs refactor?

**Comment by HenryL27** [comment]
in general I don't mind switching out conversation -> memory and interaction -> message (although I would expect that the index mappings would update to reflect this, which I might take more issue with on account of bwc). I think we should still keep the `_actionName` parts of the endpoints for clarity and consistency with the rest of the plugin unless we've decided to abandon that convention
