### ISSUE TITLE
[BUG] Security vulnerability in UpdateInteraction and memory

### ISSUE THREAD

**Issue by HenryL27** [opensearch-project/ml-commons#1901]
_I'm gonna use interaction and conversation in place of the newer message and memory bc that's still how I think about it_

**What is the bug?**
I believe a bunch of memory APIs are currently insecure (I haven't tested them but I know the code pretty well)
1. GetInteraction: recently the `conversation_id` arg to this API was removed, I guess because it made the API ugly or something. This argument was used to check whether the person asking to see a particular interaction has access to it, since conversation ownership info is stored in the top level conversation object. Thus if Bob leaks an interaction id in a secured conversation, everyone can now see that interaction, regardless of whether they have access to the conversation.
2. GetTraces: this was never designed with security in mind, as far as I can tell. Anyone is allowed to call this provided they have an interaction id.
3. UpdateInteraction: this bypasses the memory layer entirely, allowing anyone to update any interaction. You can invent or delete a lot of data like that.
4. UpdateConversation: this is the most egregious. Like UpdateInteraction, this API bypasses the memory layer and performs no security checks. Moreover, I think it can be used to 'update' the owner field of the conversation object - which allows a trivial attack of granting yourself access to a conversation (or taking it away from someone else).

**How can one reproduce the bug?**
See the descriptions. Run opensearch with security enabled and all of this should be obvious.

**What is the expected behavior?**
All of these APIs should be locked down. I can only read from or update interactions in conversations that I own.

**Do you have any additional context?**
The pentesters are gonna have a field day with this.

**Comment by Zhangxunmt** [comment]
This issue will be fixed together with the Pen test results. It's worth a discussion with the security engineer to check if we need to add user based permission check for both conversation and interaction.

**Comment by Zhangxunmt** [comment]
Permission checks for these APIs are merged in.
