### ISSUE TITLE
[BUG]The ML blueprint for SageMaker requires preprocessor and post processor 

### ISSUE THREAD

**Issue by Arukris** [opensearch-project/ml-commons#1924]
**What is the bug?**
The ML blue print in this path https://github.com/opensearch-project/ml-commons/blob/2.x/docs/remote_inference_blueprints/sagemaker_connector_blueprint.md must include the pre_process_function and post_process_function for the blueprint to deploy correctly

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ylwu-amzn** [comment]
This doc updated https://github.com/opensearch-project/ml-commons/blob/2.x/docs/remote_inference_blueprints/sagemaker_connector_blueprint.md, can you take a look if that solves your problem?
