### ISSUE TITLE
[BUG] Response field is not updated when tool throws error

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/ml-commons#1932]
**What is the bug?**
When the process for conversational agent terminated, the response field of the doc in `.plugins-ml-memory-message` will never be updated and there is not a `error` field to indicate the error reason, making it difficult to debug and find the root cause from Chatbot.

**How can one reproduce the bug?**
1. Go to Chatbot in a security enabled domain, login with a limited role.
2. Click on chat
3. Type `Is there any other way to view logs, traces or metrics in the cluster?` to trigger some tools.
![image](https://github.com/opensearch-project/ml-commons/assets/13493605/61acb83b-db8d-4bc8-9a8d-a0b916b86c44)
5. When clicking how was it generated, you will find that some tools are getting triggered but failed due to lack permission.
![image](https://github.com/opensearch-project/ml-commons/assets/13493605/27327701-e82e-4c85-805b-98c01221c5ab)

**What is the expected behavior?**
1. Naming a new field `error` in interaction to indicate there is an error when generating the answer.
2. Show real error when there are any errors throw by tools, the error is important for users to ask for help and know where goes wrong.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by jngz-es** [comment]
Thanks for reporting this bug.
