### ISSUE TITLE
[FEATURE] memory id and interaction id is not return when `verbose` is false

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/ml-commons#1988]
**Is your feature request related to a problem?**
memory id and interaction id are two fields that can be used for retrieving related informations in memory layer, so they should not be hidden when verbose is set to false.

**What solution would you like?**
Return memory id and interaction id in `_execute` API no matter verbose is true or false.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by SuZhou-Joe** [comment]
@jngz-es We discussed about this feature before, could you please take a look?

**Comment by xluo-aws** [comment]
@SuZhou-Joe , what if they are not returned? Suggestions, regeneration and how to generate will not work, right?

**Comment by SuZhou-Joe** [comment]
> @SuZhou-Joe , what if they are not returned? Suggestions, regeneration and how to generate will not work, right?

Correct, those won't work.

**Comment by dhrubo-os** [comment]
Closing this issue in favor of: https://github.com/opensearch-project/ml-commons/pull/2004
