### ISSUE TITLE
[Flaky IT test] Time_out issues and java.net.ConnectException issues in flaky IT tests

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/ml-commons#2124]
**What is the bug?**
This might not be a bug in the code or IT test itself. Flaky tests are caused by the testing environment which sometimes triggered java.net.ConnectException and Time_out issues.

Examples: 
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/7900/pipeline in windows.
https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/integ-test/runs/7900/nodes/95/steps/1204/log/?start=0 in ARM.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ylwu-amzn** [comment]
>Examples:
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/7900/pipeline in windows.
https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/integ-test/runs/7900/nodes/95/steps/1204/log/?start=0 in ARM.

Seems these two links expire. @Zhangxunmt Do you know which test case is flaky and the error log ?
