### ISSUE TITLE
[BUG] OS ignore Offline Mode?

### ISSUE THREAD

**Issue by manzke** [opensearch-project/ml-commons#2165]
I'm running OS 2.11. in a docker container with no internet and I can see after deploying a model / registering a model group.

[2024-02-28T12:00:54,931][WARN ][a.d.h.z.HfModelZoo ] [...] Failed to download Huggingface model zoo index: NLP.FILL_MASK

I've set in ENV
- HF_DATASETS_OFFLINE=1
- TRANSFORMERS_OFFLINE=1
- HF_HUB_OFFLINE=1

HfModelZoo has its own config?

**Comment by manzke** [comment]
Mentioned as improvement here https://github.com/opensearch-project/ml-commons/issues/1902

**Comment by manzke** [comment]
@zane-neo anyone? :)

**Comment by ylwu-amzn** [comment]
@manzke  Let's discuss on this https://github.com/opensearch-project/ml-commons/issues/1902 ?

**Comment by manzke** [comment]
Closing in favor of #1902
