### ISSUE TITLE
"request_body": "${parameters.input}", should be "request_body": "${parameters.inputs}",

### ISSUE THREAD

**Issue by jtrollin** [opensearch-project/ml-commons#2189]
https://github.com/opensearch-project/ml-commons/blob/2e0946aed3887588fcfcada0dc7967bf7a815550/docs/tutorials/aws/semantic_search_with_sagemaker_embedding_model.md?plain=1#L195

"request_body": "${parameters.input}", should be "request_body": "${parameters.inputs}",

**Comment by Zhangxunmt** [comment]
It's a little bit confusing. In the demo showcase that we used sageMaker, we used ${parameters.inputs} in the sageMaker connector, but the pre/post-processing functions are provided manually in the connector. For example, https://github.com/opensearch-project/ml-commons/blob/2e0946aed3887588fcfcada0dc7967bf7a815550/docs/tutorials/conversational_search/conversational_search_with_Cohere_Command.md.

**Comment by jtrollin** [comment]
"input" is correct, but you are right there are places where it has "inputs" which is what had me confused, but the code is looking for "input"

**Comment by Zhangxunmt** [comment]
Thanks for your feedback.
