### ISSUE TITLE
[BUG] text similarity model chunks showing as text embedding

### ISSUE THREAD

**Issue by HenryL27** [opensearch-project/ml-commons#2197]
**What is the bug?**
Pretrained models model chunks are showing as TEXT_EMBEDDING for TEXT SIMILARITY models

**How can one reproduce the bug?**
```
POST /_plugins/_ml/models/_register
{
  "name": "huggingface/cross-encoders/ms-marco-MiniLM-L-12-v2",
  "version": "1.0.2",
  "model_format": "TORCH_SCRIPT"
}
```
Then search for model chunks (filter algorithm=TEXT_EMBEDDING) and see 
```{
        "_index": ".plugins-ml-model",
        "_id": "2VlDC44BhsN38GR22JzJ_13",
        "_version": 1,
        "_seq_no": 0,
        "_primary_term": 1,
        "_score": 0.2876821,
        "_source": {
          "model_version": "1",
          "created_time": 1709585997320,
          "chunk_number": 13,
          "last_updated_time": 1709585997320,
          "model_format": "TORCH_SCRIPT",
          "name": "huggingface/cross-encoders/ms-marco-MiniLM-L-12-v2",
          "model_id": "2VlDC44BhsN38GR22JzJ",
          "total_chunks": 14,
          "algorithm": "TEXT_EMBEDDING"
        }
```

**What is the expected behavior?**
TEXT_SIMILARITY chunks should think they're TEXT SIMILARITY, not TEXT_EMBEDDING

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by HenryL27** [comment]
@dhrubo-os I can't repro this

**Comment by dhrubo-os** [comment]
Seems like that was a false alarm. I can't reproduce the issue now in my end either.
