### ISSUE TITLE
[FEATURE] Add hidden agent

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#2226]
**Is your feature request related to a problem?**
When an Agent using a hidden model, this agent should also be hidden.

**What solution would you like?**
Create is_hidden flag for agent.

**What alternatives have you considered?**
Just filter out the hidden model information from get/search agent API response.

**Do you have any additional context?**
N/A

**Comment by jngz-es** [comment]
https://github.com/opensearch-project/ml-commons/pull/2204
