### ISSUE TITLE
[FEATURE] Basic guardrails for remote model input and output

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#2227]
**Is your feature request related to a problem?**
LLM may generate biased/impolite/hate outputs. We need to build guardrail to block such result.

**What solution would you like?**
Add basic guardrail based on stop words and regex. If model input and output contains stop word or regex, will throw exception. This will be released in 2.13.

**What alternatives have you considered?**
No

**Do you have any additional context?**
We plan to add guardrail based on other guardrail service and semantic after 2.13.

**Comment by chishui** [comment]
Can this guardrail be turned on and off by users?

**Comment by jngz-es** [comment]
https://github.com/opensearch-project/ml-commons/pull/2209
