### ISSUE TITLE
[Discussion] Remove unnecessary setting in 2.14

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/ml-commons#2259]
**What is the bug?**
Lots of settings are added for existing features. We should consider removing some of them after they are GA for a while. 

The settings that are agreed to be removed: 
~~~
ML_COMMONS_MEMORY_FEATURE_ENABLED - plugins.ml_commons.memory_feature_enabled
ML_COMMONS_RAG_PIPELINE_FEATURE_ENABLED - plugins.ml_commons.rag_pipeline_feature_enabled
~~~

Under discussion: 
~~~
ML_COMMONS_MODEL_AUTO_REDEPLOY_ENABLE - plugins.ml_commons.model_auto_redeploy.enable
ML_COMMONS_REMOTE_INFERENCE_ENABLED - plugins.ml_commons.remote_inference.enabled
ML_COMMONS_AGENT_FRAMEWORK_ENABLED - plugins.ml_commons.agent_framework_enabled
ML_COMMONS_MODEL_AUTO_REDEPLOY_LIFETIME_RETRY_TIMES - plugins.ml_commons.model_auto_redeploy.lifetime_retry_times
~~~

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ylwu-amzn** [comment]
Why remove these settings ? If user don't want to use these features, how they disable it?

**Comment by dhrubo-os** [comment]
Why should we consider this as a `bug`?

**Comment by Zhangxunmt** [comment]
The conversational search can be considered as a standard search feature like KNN so no feature flag needed? Like we do search in OS, we don't need to open a flag to do that. I think Aryn has agreed for these two settings for memories. 

For other settings, let's discuss them in the next community meeting. It's not a Bug but Github only provided that sample by default.

**Comment by ylwu-amzn** [comment]
I would suggest keep the settings to keep the flexibility for advanced user who may want to customize.

**Comment by austintlee** [comment]
@Zhangxunmt can you open a separate issue to discuss the default for `ML_COMMONS_ONLY_RUN_ON_ML_NODE`?

**Comment by Zhangxunmt** [comment]
@austintlee, Yes I just removed ML_COMMONS_ONLY_RUN_ON_ML_NODE out from this discussion.
