### ISSUE TITLE
[FEATURE] Add retry mechanism so predict API can success in node crash case

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/ml-commons#2327]
**Is your feature request related to a problem?**
Currently ml-commons predict API doesn't have retry mechanism so when encountered node crash case, user will get failure results, e.g.: A cluster has two nodes A and B, both nodes has a model routing table internally, when A received a request, it will dispatch to B or process by itself based on round robin. Let's say A dispatched the request to B and B crashed, then user will get error response.

**What solution would you like?**
We should add retryableListener to handle this case, when it's an retryable exception we can retry by dispatching the request to next node.

**What alternatives have you considered?**

**Do you have any additional context?**
This is more like a general issue and this can be made in OpenSearch core, so other plugins have the similar issue can rely on this as well, created an issue in OpenSearch core regarding this: https://github.com/opensearch-project/OpenSearch/issues/13157

**Comment by ylwu-amzn** [comment]
Conern: which use case/exceptionw we should retry
Nueralsearch already has retry now, should we add in ml-commons

**Comment by Zhangxunmt** [comment]
Discussed this issue in the community meeting. Let's keep this "Predict" as the lowest level API call and leave the retry to the upper level applications. At least we should disable this retry by default and make it optional. Enforcing a retry logic in "Predict" may add overhead to all apps that depends on ml-commons even they don't need retry.

**Comment by zane-neo** [comment]
Closing this since this doesn't seem an issue as of now.
