### ISSUE TITLE
[Enhancement] Add default multi-modal process function in ml-commons

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/ml-commons#2364]
**Is your feature request related to a problem?**
multi-modal is an already supported feature in neural-search and ml-commons, but now in ml-commons we need to write painless scripts to pre/post-process functions the inputs/outputs of multi-modal requests which is inconvenient for users.

**What solution would you like?**
We can add default pre/post process functions for multi-modal case so user can use very simple string to configure their connectors. 

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by dhrubo-os** [comment]
@zane-neo are you planning to release this enhancement in 2.15? What's the plan?

**Comment by zane-neo** [comment]
> @zane-neo are you planning to release this enhancement in 2.15? What's the plan?

This will be released in 2.16.
