### ISSUE TITLE
[META] Auto undeploy ML Model with TTL

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#2376]
**Is your feature request related to a problem?**
As we continue to develop and utilize numerous Machine Learning models, management and resource optimization have become essential. In particular, we need a mechanism to automatically undeploy the models after they've reached a specific Time To Live (TTL). This TTL limit proposes undeploying models that have been inactive or unused for a particular defined period.

**What solution would you like?**
Add model TTL to deploy setting. Automatic tracking of model usage or last accessed timestamp to understand if a model should be undeployed. Auto-undeployment should clean up all associated resources to conserve server memory, disk space, or any other resources the models may be using.

**What alternatives have you considered?**
Keep the same with current user experience. User need to manually undeploy model 

**Do you have any additional context?**
No

**Comment by Zhangxunmt** [comment]
https://github.com/opensearch-project/documentation-website/pull/7083
