### ISSUE TITLE
[FEATURE] Support remote guardrails model

### ISSUE THREAD

**Issue by jngz-es** [opensearch-project/ml-commons#2377]
**Is your feature request related to a problem?**
Improve guardrails performance.

**What solution would you like?**
Call remote guardrails model to check user input and model output.

**What alternatives have you considered?**
We already have an alternative using stop words and regex to validate input/output.

**Do you have any additional context?**
None.

**Comment by xinyual** [comment]
Do we have any design for that? For example, we will call it parallel when we using agent execute API? Can we design it as a function/method so I can reuse it in PPL Tool in skills repo?

**Comment by jngz-es** [comment]
Hi @xinyual , we plan to only add a new type for the current guardrail implementation. I believe you can reuse it for PPL tool, as it works on model level, runs in model prediction process. So it doesn't matter with agent execute API.
