### ISSUE TITLE
[ENHANCEMENT] Avoid un-necessary predictions in ingest processors

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/ml-commons#2413]
**Is your feature request related to a problem?**
When re-indexing, `text_embedding` processors and `ml_inference` processors will run the prediction again even when the inference fields are already existed in the document. `text_embedding` processors will over-write the the inference field, while `ml_inference` will not write to the inference field, then throw exception or skip writing to the document.  

**What solution would you like?**
In the ingest processor that used ml inference, we should check the model output field name, for example, `text_embedding` field exists in the document before the prediction tasks run. If the field already exists, skip the predictions. 

In this case, when re-index happens, it won't run the prediction tasks again if the field is existed. 

**What alternatives have you considered?**
Welcome any other suggestions.

**Comment by IanMenendez** [comment]
Maybe it would be nice to add a parameter on ml ingest processors called `overwrite: Option[Boolean]` if true it overwrites current embeddings upon reindexing if false it does not overwrite 

I is nice to still have the option to overwrite in case we change the ML model that outputs different embeddings

**Comment by ylwu-amzn** [comment]
Added in this PR https://github.com/opensearch-project/ml-commons/pull/2508
