### ISSUE TITLE
[BUG] Failed to delete model 

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#2419]
**What is the bug?**

Undeploy Response is successful with state as "undeployed" and when we try to delete the model, It is throwing an error saying model cannot be deleted in deploying or deployed state. The calls were within milliseconds.

**How can one reproduce the bug?**

**What is the expected behavior?**
If undeploy API return successfully, it should mean the model deployed and model state flushed to index correctly.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ylwu-amzn** [comment]
@b4sjoo Can you help take a look ?

**Comment by b4sjoo** [comment]
Ok, let me try if I can reproduce it. I think it is a little bit flaky.

**Comment by b4sjoo** [comment]
According to our investigation, this is because when we return the undeploy response the cluster might still be executing `syncUpUndeployedModels` task. The above PR should fix the issue by wrapping it with the listener.

**Comment by zhichao-aws** [comment]
Seems #1986 has the same root cause

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain)]
