### ISSUE TITLE
[RFC] Add retry with backoff for SageMaker throttling exception to mitigate the data lost problem

### ISSUE THREAD

**Issue by zhichao-aws** [opensearch-project/ml-commons#2438]
## Problem Statement
related issue: #2429 
Some OpenSearch users deploy their ML models at SageMaker to encode documents. But some times users get throttling exceptions, especially during ingestion, even with bulk size 100. It is hard to diagnose the problem, and the failed documents won't be ingested (may lead to data lost). This problem harms the user experience with several main perspectives:

### 1. Error log is hard to diagnose
With a bulk request, the throttled documents fail, but other documents success. And the entire bulk request don’t throw exception. The response looks like this:
```json
{
  "took": 71,
  "ingest_took": 4444,
  "errors": true,
  "items": [
    {
      "index": {
        "_index": "scifact",
        "_id": "33",
        "status": 400,
        "error": {
          "type": "status_exception",
          "reason": "Error from remote service: {\"message\":null}"
        }
      }
    },
    ...
  ]
}
```
If the exception is not handled by client, data is lost. The exception information is in the response header and is hard to diagnose.

### 2. Users get throttling exception even without large workload
As mentioned before, we can still get the throttling exception even with a single bulk request of size 100. The SageMaker endpoint can definitely handle it (in fact, the maximum throughput is ~300 docs/s in our experiments). And this harms customer experience a lot, they have to split one bulk request to smaller ones. 

## Solution
SageMaker throttles the requests by max concurrent request numbers. I set up an endpoint with pseudo handler, which just sleep 50ms and return a fix vector. This pseudo handler consumes little CPU/GPU resources, but I can still get throttling exception.

We can devide the throttling scenerio by 2 cases: 1. users do have large workload 2. users don't have large workload, but they get throttled because the bulk request invoke the SageMaker for each document, leading to large concurrent requests. For case 1, the user has to upgrade to a stronger SageMaker instance or use more instances. For case 2, we can mitigate this problem by adding strategy of retry with exponential backoff.

## experiments
I did some experiments at my side to verify the feasibility of retry with backoff.
I use the [neural sparse model](https://huggingface.co/opensearch-project/opensearch-neural-sparse-encoding-v1) and ml.g4dn.xlarge. (deployment script reference [link](https://github.com/zhichao-aws/neural-search/tree/neural_sparse_sagemaker/neural_sparse_sagemaker_example), here I turn off the async logging for stable performance). All documents consist of fixed 128 tokens.
The basic backoff time is 50ms, 100ms, 200ms, 400ms, 800ms here for each retry.

|                                              | bulk size | client num | mean throughput | api error rate | doc lost rate | SageMaker endpoint inference throughput (mean throughput * (1 - doc lost rate)) |
| -------------------------------------------- | --------- | ---------- | --------------- | -------------- | ------------- | --------------------------------------- |
| no retry                                     | 10        | 4          | 296.8           | 0              | 0             | 296                                     |
| no retry                                     | 10        | 8          | 310.18          | 10.38%         | 1.14%         | 306                                     |
| no retry                                     | 10        | 12         | 334.12          | 37%            | 8.50%         | 305                                     |
| no retry                                     | 200       | 1          | 329.74          | 100%           | 25.30%        | 246                                     |
| no retry                                     | 2000      | 1          | 519.5           | 100%           | 44.14%        | 290                                     |
| retry with exponential backoff (max retry 3) | 10        | 4          | 296.17          | 0              | 0             | 296                                     |
| retry with exponential backoff (max retry 3) | 10        | 8          | 302.4           | 0.06%          | 0.01%         | 302                                     |
| retry with exponential backoff (max retry 3) | 10        | 12         | 302.31          | 0.67%          | 0.07%         | 302                                     |
| retry with exponential backoff (max retry 3) | 200       | 1          | 271.52          | 0              | 0             | 271                                     |
| retry with exponential backoff (max retry 3) | 2000      | 1          | 295.9           | 0              | 0             | 295                                     |
| retry with exponential backoff (max retry 5) | 10        | 8          | 313.83          | 0              | 0             | 313                                     |
| retry with exponential backoff (max retry 5) | 10        | 12         | 300.92          | 0              | 0             | 300                                     |

### Conclusion
We have several observations based on experiments result:
1. Without retry, the doc lost rate is high with bulk size increase. And we can still see doc lost when the bulk size is small but concurrency is high (8, 12 clients).
2. Retry with 3 times can mitigate this problem effectively. The doc lost rate is very small(<0.1%) and only exists at high concurrency. And the exponential backoff doesn't affect the performance here. If we increase the max retry time to 5, we don't see any exceptions here.
3. With large bulk size (5000, 8000), we start to see exception of `all error caused by: Error communicating with remote model: Acquire operation...` (detailed log put at the appendix). And the error rate is not stable(from 1% to 40% in my experiments).  This exception is about too long waiting time for async client netty io, it's new feature in 2.14 and I think we can track this in a seperate section cc @zane-neo . But I guess it's not a critical problem in 2.14 release because users will get throttling exception first.

## Todo
1. Improve the log about SageMaker throttling exception. Instead of message null, we should wrap the exception with new class like ThrottlingException or RetryableException (used for retry), and give more precise error message.
2. Implement retry with exponential backoff. It should only work for remote connector, and only retry for retryable exception (we can go with SageMaker throttling exception first). We can make it configurable through cluster settings.

## Appendix
1. experiments settings
I use local cluster by running `./gradlew run -PnumNodes=3`. And use benchmark-tool to invoke the bulk request. One example config:
```json
{
    "operation": {
        "operation-type": "bulk",
        "bulk-size": 10
    },
    "clients": 4,
    "warmup-iterations": 0,
    "iterations": 200
}
```
2. error log for `Error communicating with remote model: Acquire operation...`
```
[2024-05-09T17:26:08,748][ERROR][o.o.m.e.a.r.MLSdkAsyncHttpResponseHandler] [integTest-2] Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.decorateException(NettyUtils.java:69) ~[netty-nio-client-2.25.40.jar:?]
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:307) [netty-nio-client-2.25.40.jar:?]
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.makeRequestListener(NettyRequestExecutor.java:188) [netty-nio-client-2.25.40.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:503) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.108.Final.jar:4.1.108.Final]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.util.concurrent.TimeoutException: Acquire operation took longer than configured maximum time
	at software.amazon.awssdk.http.nio.netty.internal.utils.BetterFixedChannelPool.<init>(...)(Unknown Source) ~[?:?]
```

**Comment by zhichao-aws** [comment]
I can be asigned for implenting the todos in this RFC

**Comment by zane-neo** [comment]
For issue 2 in appendix, did you try to increase max connections in connector configuration? Also, please refer to this: https://github.com/opensearch-project/OpenSearch/issues/13157 see if the retry can be implemented in a general approach.

**Comment by zhichao-aws** [comment]
I just tried using a smaller `max_connection` to limit the max concurrent request from OpenSearch. And after I decreased it to 10 (3 nodes, 3*10=30 total concurrency), I didn't get the throttling exception anymore. And the ingestion throughput is still as high as the experiments before.

So to fix the throttling totally, users should set a proper `max_connection` when create connector. But here are several drawbacks:
1. The max connection threshold is unclear at SageMaker point. Users may need to adjust the `max_connection` to get the  proper value.
2. There can be other clients calling the target SageMaker endpoint. Restricting the concurrency at our-side can not guarantee there is no throttling exception. Since the throttling will cause data lost, we should avoid the case that throttling exception not handled.

As a result, we need to inform users about the `max_connection` setting, and we should also implement the retry logic in parallel. The retry logics implement a self-adaption concurrency control at OpenSearch side. It can help mitigate the throttling exception whether tuning or not tuning the `max_connection`. 

cc @ylwu-amzn @zane-neo

**Comment by Zhangxunmt** [comment]
The SageMaker throttling depends on SM instance type and number of instances behind the endpoint. With a powerful instance or more hosts in SM, the throttling rate will be higher. In openSearch, this max_connection also depends on number of data nodes in the cluster. It's not a fixed number that we should just set a smaller number. The smaller the max_connection, the slower the ingestion performance.

**Comment by zhichao-aws** [comment]
|                                              | bulk size | client num | mean throughput | api error rate | doc lost rate | SageMaker endpoint inference throughput (mean throughput * (1 - doc lost rate)) |
| -------------------------------------------- | --------- | ---------- | --------------- | -------------- | ------------- | --------------------------------------- |
| retry with constant backoff                                     | 10        | 4          | 297.6           | 0              | 0             | 297.6                                     |
| retry with constant backoff                                 | 10        | 12          | 305.2          | 0         | 0         | 305.2                                    |
| retry with constant backoff                                | 2000        | 1         | 292.73          | 0            |0         | 292.73                                  |
