### ISSUE TITLE
[BUG] agent execution error message

### ISSUE THREAD

**Issue by jngz-es** [opensearch-project/ml-commons#2443]
**What is the bug?**
Agent execution api will return the following error message if the root cause exception doesn't occur in coordinate node and is wrapped into remote transport exception.
```
"{\"error\":{\"reason\":\"Invalid Request\",\"details\":\"[d0aa9b912dfc3dacaf11334ad978ea34][x.x.x.x:x][cluster:admin/opensearch/ml/execute]\",\"type\":\"RemoteTransportException\"},\"status\":400}"
```

**Comment by yuye-aws** [comment]
This info might help you: the wrapped "so-called" remote transport exception is actually of type ResponseException
