### ISSUE TITLE
[FEATURE] Add connector blueprints for Amazon Comprehend APIs

### ISSUE THREAD

**Issue by tkykenmt** [opensearch-project/ml-commons#2467]
**Is your feature request related to a problem?**
Add AI connector blueprint for Amazon Comprehend APIs in addition to existing ones. If it is already a plan in future release, please close this issue.

**What solution would you like?**
Markdown files of Amazon Comprehend connector blueprint and instruction to create ingestion pipeline with ml-inference processor for embedding metadata such as detected languages, detected entities or detected toxic phrase.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by tkykenmt** [comment]
I've already created blueprint for Amazon Comprehend connector. I'll create new PR if this issue meets a bar for contribution.

**Comment by ylwu-amzn** [comment]
@tkykenmt Thanks for creating this issue. Feel free to create PR for blueprint for Amazon Comprehend connector

**Comment by tkykenmt** [comment]
PR is merged and closed.
