### ISSUE TITLE
[BUG] Minimum supported version check requires that minimum version to compile

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/ml-commons#2483]
**What is the bug?**

In the 2.14 release, two constants were added to gate features based on versions below 2.14:
```java
    public static final Version MINIMAL_SUPPORTED_VERSION_FOR_INTERFACE = Version.V_2_14_0;
    public static final Version MINIMAL_SUPPORTED_VERSION_FOR_MODEL_TTL = Version.V_2_14_0;
```

Unfortunately, those version constants are only available in the OpenSearch 2.14.0 (and later) dependency, which means that we must be on 2.14 (or later) to compile the plugin, and these gating checks are essentially useless.

There are similar constants for other minimal supported versions going back to 2.11.0 which are all essentially useless.

**How can one reproduce the bug?**
1. On the 2.x branch, change the version in `build.gradle` to a version before 2.14.0
2. Run `./gradlew assemble` (or any command that compiles the source)
3. Observe compile failures on the above constants

**What is the expected behavior?**

Code below the minimal supported versions can use those constants as feature support checks.

**Do you have any additional context?**

This impacts support using current 2.x-based feature branches on other environments still using 2.13 as a fixed version.

The code can easily be replaced by a calculation of the `Version` from a string:
```java
Version.fromString("2.14.0")
```

**Comment by ylwu-amzn** [comment]
@b4sjoo Can you help take a look ?

**Comment by dbwiddis** [comment]
@ylwu-amzn @b4sjoo I'll be making a quick fix for the 2.14 one on the feature/multi_tenancy branch, I can easily submit one on main a little bit later.

**Comment by dbwiddis** [comment]
Also the `GenerativeQAResponseProcessor` class imports `PipelineProcessingContext` from OpenSearch, requiring v. 2.12.0 or later.

**Comment by b4sjoo** [comment]
I think @dbwiddis provided a good fix for this issue
