### ISSUE TITLE
[BUG] Can't generate multiple embeddings with Bedrock embedding model

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#2490]
**What is the bug?**
Bedrock embedding model can't generate embeddings for multiple text inputs.

**How can one reproduce the bug?**
1. Create OpenSearch 2.14 cluster
2. Create Bedrock embedding model with this blueprint https://github.com/opensearch-project/ml-commons/blob/2.x/docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md
3. Run predict
```
POST _plugins/_ml/_predict/text_embedding/<model_id>
{
  "text_docs":[ "hello world", "today is sunny"],
  "return_number": true,
  "target_response": ["sentence_embedding"]
}
```
Can see only one embedding generated. 

**What is the expected behavior?**
Should generate embeddings for all text inputs.

**What is your host/environment?**
 - OS: Linux
 - Version: 2.14
 - Plugins

**Do you have any screenshots?**
No

**Do you have any additional context?**
No

**Comment by ylwu-amzn** [comment]
@zane-neo This caused by https://github.com/opensearch-project/ml-commons/pull/1958. Can you help fix this ?

**Comment by zane-neo** [comment]
This has a workaround which is to update the connector info adding step size like below:
```
PUT /_plugins/_ml/connectors/{connector_id}
    "parameters": {
        "service_name": "bedrock",
        "input_docs_processed_step_size": "1",
        "region": "{your_region}"
    }
}
```
Also, will create PR to fix this.

**Comment by zane-neo** [comment]
Closing this issue as it is resolved now.
