### ISSUE TITLE
[FEATURE] Support for Code Interpreter Tool like E2B so that we can run any Python Code using Interpreter tool once code generated by LLM

### ISSUE THREAD

**Issue by ramda1234786** [opensearch-project/ml-commons#2493]
**Is your feature request related to a problem?**
With Agents not able to run code generated by LLM.
Just like we have Tools for Index, Mapping, VectorDB, RAG, we can also have it for `Code Interpreter` Tool.

One example is here 
https://github.com/e2b-dev/code-interpreter

**What solution would you like?**
Once the LLM Generated the Code, we should be run them. To start with Python Language
Should be able to Run the Code also when passing the code to the Agentic Workflow

**What alternatives have you considered?**
Using some other Agentic Tool like LlamaIndex with OpenSearch Vector Index, but this does not sound to be good solution

**Do you have any additional context?**
With this code interpreter we should be able to check the code response live by running them with the Agent Itself

**Comment by ylwu-amzn** [comment]
We are building a connector tool which allows Agent to call external service. If this Code Interpreter has REST API (or you can simply wrap it into a REST API), then you can use the connector tool to call external service.

**Comment by ramda1234786** [comment]
okay great. Thanks

**Comment by ylwu-amzn** [comment]
@ramda1234786  I will close this one as we are going to build Connector Tool (https://github.com/opensearch-project/ml-commons/issues/2497) which can support this. Feel free to open if you think it's going to be a different feature.
