### ISSUE TITLE
[FEATURE] Build connector tool

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#2497]
We have released AgentFramework in OS 2.13. It supports a set of [tools](https://opensearch.org/docs/latest/ml-commons-plugin/agents-tools/tools/index/). 

We plan to add a new ConnectorTool which leverage current connector framework to call any REST APIs.

**Comment by ramda1234786** [comment]
any release timeline for this?

**Comment by ylwu-amzn** [comment]
@ramda1234786 , plan to release in 2.15

**Comment by ramda1234786** [comment]
Thanks @ylwu-amzn , surely will try very first day.
