### ISSUE TITLE
[BUG] Cannot add openai embedding connector in dev tools

### ISSUE THREAD

**Issue by max-tano** [opensearch-project/ml-commons#2498]
**Describe the bug**
When i follow the [steps](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ml-external-connector.html) to add a external connector i always get a 502.

Here is a sample of a post i put in the dev console

POST /_plugins/_ml/connectors/_create
{
    "name": "embedding_ada",
    "description": "My connector to create embedding using ada model",
    "version": "1.0",
    "protocol": "http",
    "parameters": {
        "model": "text-embedding-ada-002"
    },
    "credential": {
        "openAI_key": "Bearer key"
    },
    "actions": [
        {
        "action_type": "predict",
        "method": "POST",
        "url": "https://api.openai.com/v1/embeddings",
        "headers": {
            "Authorization": "Bearer ${credential.openAI_key}"
        },
        "request_body": "{ \"input\": ${parameters.input}, \"model\": \"${parameters.model}\" }",
        "pre_process_function": "connector.pre_process.openai.embedding",
        "post_process_function": "connector.post_process.openai.embedding"
        }
    ]
}

An this also returns a 502 "Request failed to get to the server (status code: 502)"

Please lmk when this is fixed

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ylwu-amzn** [comment]
@max-tano  which version are you using ? If you are using AWS managed OpenSearch service, you can refer to this tutorial https://github.com/opensearch-project/ml-commons/blob/2.x/docs/tutorials/aws/AIConnectorHelper.ipynb or https://github.com/opensearch-project/ml-commons/blob/2.x/docs/tutorials/aws/semantic_search_with_openai_embedding_model.md

**Comment by max-tano** [comment]
Its version 2.13 of aws managed opensearch. I tried the second tutorial but get the same 502 response, are you able to connect a external model (for example open ai ada 2)?

**Comment by ylwu-amzn** [comment]
@max-tano  It should work, can you try the first tutorial which is much easier ?

**Comment by ylwu-amzn** [comment]
@drobbins-ancile , @max-tano Sorry for replying late. Let's have a call to go through the error? I tried on Amazon managed OpenSearch 2.13 by following https://github.com/opensearch-project/ml-commons/blob/2.x/docs/tutorials/aws/AIConnectorHelper.ipynb, it works.

You can join OpenSearch community slack https://join.slack.com/t/opensearch/shared_invite/zt-2kgztctzr-kVrVcH1~sq5f85DjoDqAyA, then you can find me in the public slack channel `#ml`

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by ylwu-amzn** [comment]
If you are using AWS managed OpenSearch cluster, you should not use 
```
"credential": {
"openAI_key": "Bearer key"
},
```
Check this tutorial https://github.com/opensearch-project/ml-commons/blob/2.x/docs/tutorials/aws/semantic_search_with_openai_embedding_model.md#42-create-connector, you should use 
```
  "credential": {
    "secretArn": "your_secret_arn_created_in_step1",
    "roleArn": "your_iam_role_arn_created_in_step2"
  },
```

**Comment by ylwu-amzn** [comment]
AWS OpenSearch 2.13 restrict only `secretArn` and `roleArn` allowed

**Comment by ylwu-amzn** [comment]
Close this issue as no more comment after 4 month. Please reopen or create a new issue if need more help.
