### ISSUE TITLE
[META] Support local model in ML inference processor

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#2499]
We have released [ML inference processor](https://opensearch.org/docs/latest/ingest-pipelines/processors/ml-inference/) in 2.14 which only supports remote model. We are going to enhance it to support local model too.

**Comment by asfoorial** [comment]
Does this mean models deployed inside OpenSearch ml-common?

**Comment by dhrubo-os** [comment]
> Does this mean models deployed inside OpenSearch ml-common?

Yes, it is going to be released with 2.15. Related PR: https://github.com/opensearch-project/ml-commons/pull/2508

**Comment by asfoorial** [comment]
Great! Now is it possible to deploy a small language model such as microsoft/Phi-3-mini-4k-instruct-onnx on OpenSearch and use this feature to do question answering inferencing within OpenSearch? If yes, then would you please share the steps?

**Comment by ylwu-amzn** [comment]
@asfoorial , no, this feature is to support using current supported local models in ML inference processor. SLM is not a supported local model type. So you can't deploy it inside OpenSearch cluster. You can deploy it somewhere else and use connector to connect. One update in 2.15 is we support private IP setting https://github.com/opensearch-project/ml-commons/pull/2534
