### ISSUE TITLE
[BUG]Latency in deleteing modelgroup leading to failure of creation of modelgroup with the same name after deleting the existing modelgroup

### ISSUE THREAD

**Issue by madan-tamraparni** [opensearch-project/ml-commons#2518]
**What is the bug?**
Latency in deleteing modelgroup leading to failure of creation of modelgroup with the same name after deleting the existing modelgroup.

**How can one reproduce the bug?**
1. Create a script/function to do the below steps 
2. Create a modelgroup with any name
3. Delete the created modelgroup
4. Check the response and ensure the state is "deleted"
5. Create the model group again with the same name

**What is the expected behavior?**
ModelGroup needs to be created successfully

**Do you have any additional context?**
Observed that modelgroup creation fails because of the error 
" with error- elastic: Error 400 (Bad Request): The name you provided is already being used by a model group with ID:"

**Comment by ylwu-amzn** [comment]
Fixed in this PR https://github.com/opensearch-project/ml-commons/pull/2514
