### ISSUE TITLE
[BUG] ITs are failing due to circuit breaker exception

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/ml-commons#2528]
**What is the bug?**
There're several ITs are keep failing due to circuit breaker exception, more details can be found here: https://github.com/opensearch-project/ml-commons/actions/runs/9458233352/job/26054944600?pr=2495

**How can one reproduce the bug?**

**What is the expected behavior?**
All ITs should be able to pass successfully.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by rbhavna** [comment]
These flaky tests should be fixed with the PR by @jngz-es that disables jvm memory in circuit breaker in IT tests: https://github.com/opensearch-project/ml-commons/pull/2540
