### ISSUE TITLE
[BUG] Your request contained invalid JSON: 'utf-8' codec can't decode byte 0xeb (OpenAI connector) 

### ISSUE THREAD

**Issue by noopy0812** [opensearch-project/ml-commons#2624]
What is the bug?
I encountered an issue when attempting to return an embedding for a string containing the character "∙". The error message I received was: "Your request contained invalid JSON: 'utf-8' codec can't decode byte 0xad in position 5614: invalid start byte".
In addition to the "∙" character, when embedding approximately 1000 times, other special characters also cause similar issues. This problem has been noted previously, as seen in this link: https://github.com/opensearch-project/ml-commons/issues/1666. Could you please address this issue again?

Thank you.

Removing the special character and replacing it with " " works. If I request the embedding directly from open AI (with special character) it works fine.

How can one reproduce the bug?
Setup Open AI connector described [here](https://github.com/opensearch-project/ml-commons/blob/2.11.0.0/docs/remote_inference_blueprints/cohere_connector_embedding_blueprint.md):
Retrieve embedding for string described above.

What is the expected behavior?
Embedding should be returned for strings containing special characters.

What is your host/environment?
Opensearch 2.13 running in AWS

Do you have any screenshots?
N/A

Do you have any additional context?
N/A

**Comment by ylwu-amzn** [comment]
This is a known issue.  You can go to AWS OpenSearch console, then upgrade to `OpenSearch_2_13_R20240520-P4` to fix the issue
