### ISSUE TITLE
[BUG] Get conversation meta don't return application_type

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/ml-commons#2632]
**Is your feature request related to a problem?**

current get memory api https://opensearch.org/docs/latest/ml-commons-plugin/api/memory-apis/get-memory/ will return response like below, it miss [application_type](https://github.com/opensearch-project/ml-commons/blob/main/common/src/main/java/org/opensearch/ml/common/conversation/ConversationalIndexConstants.java#L59) field.
```
{
  "memory_id": "gW8Aa40BfUsSoeNTvOKI",
  "create_time": "2024-02-02T18:07:06.887061463Z",
  "updated_time": "2024-02-02T19:01:32.121444968Z",
  "name": "Conversation for a RAG pipeline",
  "user": "admin"
}
```

mapping of system index `.plugins-ml-memory-meta`
```
{
  ".plugins-ml-memory-meta": {
    "mappings": {
      "_meta": {
        "schema_version": 1
      },
      "properties": {
        "application_type": {
          "type": "keyword"
        },
        "create_time": {
          "type": "date",
          "format": "strict_date_time||epoch_millis"
        },
        "name": {
          "type": "text"
        },
        "updated_time": {
          "type": "date",
          "format": "strict_date_time||epoch_millis"
        },
        "user": {
          "type": "keyword"
        }
      }
    }
  }
}
```

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by Hailong-am** [comment]
@Zhangxunmt want to confirm with you does this `application_type` not return by intention? is there a specific reason or we just miss it?

**Comment by Zhangxunmt** [comment]
This is expected. Not a bug. Already discussed this issue in other threads.
