### ISSUE TITLE
[BUG] A lot of tests in ml-commons are failing due to disk circuit breaker open

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/ml-commons#2639]
**What is the bug?**
https://github.com/opensearch-project/ml-commons/actions/runs/9868776951/job/27251331931?pr=2500#step:6:3786

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by b4sjoo** [comment]
@zane-neo Hi Zan, do you know what's the circuit breaker value range for the setting you are changing?

**Comment by b4sjoo** [comment]
@zane-neo Meanwhile you need to add this setting to OpenSearch Document

**Comment by zane-neo** [comment]
@b4sjoo There's no range for this setting, this is the PR to document: https://github.com/opensearch-project/documentation-website/pull/7799/files

**Comment by ylwu-amzn** [comment]
> @b4sjoo There's no range for this setting, this is the PR to document: https://github.com/opensearch-project/documentation-website/pull/7799/files

Can you test? I think should be >=0 ?

**Comment by zane-neo** [comment]
> > @b4sjoo There's no range for this setting, this is the PR to document: https://github.com/opensearch-project/documentation-website/pull/7799/files
> 
> @zane-neo Can you test? I think should be >=0 ?

Checked, it's [-1, Long.MAX_VALUE] and updated to the document.
