### ISSUE TITLE
[BUG] ChatAgentRunner extract final_answer incorrectly when having wrapping lines

### ISSUE THREAD

**Issue by qianheng-aws** [opensearch-project/ml-commons#2649]
**What is the bug?**
When the response of LLM is a string of wrapping lines, it extract the final answer incorrectly with redundant characters **`" }`**

```
Response of LLM:

The alert has been successfully created based on the input provided. The key details are:
```json
{
    "thought": "Now I know the final answer",
    "final_answer": "The alert ‘Error Response Alert’ has been created with the following configuration:
- Indices: opensearch_dashboards_sample_data_logs
- Time field: timestamp
- Bucket interval: 60 minutes
- Filters: response is not 200
- Aggregation: Count of bytes field
- Trigger: ‘Error Response Count Above 50’ - severity 1, threshold 50 (above)
This alert will trigger when the error response count exceeds 50 per 60 minute interval."
}
```. 

Final Answer:

The alert ‘Error Response Alert’ has been created with the following configuration:
- Indices: opensearch_dashboards_sample_data_logs
- Time field: timestamp
- Bucket interval: 60 minutes
- Filters: response is not 200
- Aggregation: Count of bytes field
- Trigger: ‘Error Response Count Above 50’ - severity 1, threshold 50 (above)
This alert will trigger when the error response count exceeds 50 per 60 minute interval.”
}

```

**How can one reproduce the bug?**
It's flaky and depends on whether the response string is compatible with  `org.opensearch.ml.common.utils.StringUtils.isJson`. In my response above, the method `isJson` returns false when calling `AgentUtils::parseThoughtResponse` as it has wrapping lines. Then it fallback to `extractFinalAnswer` to get final answer, but the match pattern is 
``` String pattern = "\"final_answer\"\\s*:\\s*\"(.*?)$";``` which leads to match `" }` as well in the result.

**What is the expected behavior?**
The final answer should be:
```
The alert ‘Error Response Alert’ has been created with the following configuration:
- Indices: opensearch_dashboards_sample_data_logs
- Time field: timestamp
- Bucket interval: 60 minutes
- Filters: response is not 200
- Aggregation: Count of bytes field
- Trigger: ‘Error Response Count Above 50’ - severity 1, threshold 50 (above)
This alert will trigger when the error response count exceeds 50 per 60 minute interval.
```

**What is your host/environment?**
 - OS: [e.g. macos]
 - Version [e.g. 3.0.0-SNAPSHOT]
 - Plugins: alert, ml-commons, skills

**Do you have any screenshots?**
![image](https://github.com/user-attachments/assets/8b92bff2-ee5c-432a-a03c-863e2c69e3cd)
**Do you have any additional context?**
Add any other context about the problem.

**Comment by b4sjoo** [comment]
@jngz-es Hi Jing, please take a look on this issue since you are the feature owner
