### ISSUE TITLE
[Enhancement] Add a new field `additional_info` for memory metadata

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/ml-commons#2755]
**Is your feature request related to a problem?**

I would like have a field to store some additional information about the memory metadata, for example agent id or prompt information into this additional info for the memory metadata

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**
perviously we want to reuse application type and have an issue
https://github.com/opensearch-project/ml-commons/issues/2632, but this field is not intend to expose to end user.

**Comment by ylwu-amzn** [comment]
I think we should call this as enhancement

**Comment by Hailong-am** [comment]
close it as PR merged
