### ISSUE TITLE
[BUG] Failure in createConnector should not log API keys. 

### ISSUE THREAD

**Issue by austintlee** [opensearch-project/ml-commons#2915]
**What is the bug?**
It looks like the error message in the CreateConnector failure response contains the API key in the template.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by austintlee** [comment]
``
RestMLRemoteInferenceIT > testDeleteConnector FAILED
    org.opensearch.client.ResponseException: method [POST], host [http://127.0.0.1:55810], URI [/_plugins/_ml/connectors/_create], status line [HTTP/1.1 503 Service Unavailable]
    {"error":{"root_cause":[{"type":"unavailable_shards_exception","reason":"[.plugins-ml-connector][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[.plugins-ml-connector][0]] containing [index {[.plugins-ml-connector][bnO6yZEB1QdOTLrBQkCP], source[{\"name\":\"OpenAI Connector\",\"version\":\"1\",\"description\":\"The connector to public OpenAI model service for GPT 3.5\",\"protocol\":\"http\",\"parameters\":{\"endpoint\":\"api.openai.com\",\"content_type\":\"application/json\",\"auth\":\"API_Key\",\"max_tokens\":\"7\",\"temperature\":\"0\",\"model\":\"gpt-3.5-turbo-instruct\"},\"credential\":{\"openAI_key\":\"<api key>\"},\"actions\":[{\"action_type\":\"PREDICT\",\"method\":\"POST\",\"url\":\"https://${parameters.endpoint}/v1/completions\",\"headers\":{\"Authorization\":\"Bearer ${credential.openAI_key}\"},\"request_body\":\"{ \\\"model\\\": \\\"${parameters.model}\\\", \\\"prompt\\\": \\\"${parameters.prompt}\\\",  \\\"max_tokens\\\": ${parameters.max_tokens},  \\\"temperature\\\": ${parameters.temperature} }\"}],\"client_config\":{\"max_connection\":20,\"connection_timeout\":50000,\"read_timeout\":50000,\"retry_backoff_millis\":200,\"retry_timeout_seconds\":30,\"max_retry_times\":0,\"retry_backoff_policy\":\"constant\"}}]}] and a refresh]"}],"type":"unavailable_shards_exception","reason":"[.plugins-ml-connector][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[.plugins-ml-connector][0]] containing [index {[.plugins-ml-connector][bnO6yZEB1QdOTLrBQkCP], source[{\"name\":\"OpenAI Connector\",\"version\":\"1\",\"description\":\"The connector to public OpenAI model service for GPT 3.5\",\"protocol\":\"http\",\"parameters\":{\"endpoint\":\"api.openai.com\",\"content_type\":\"application/json\",\"auth\":\"API_Key\",\"max_tokens\":\"7\",\"temperature\":\"0\",\"model\":\"gpt-3.5-turbo-instruct\"},\"credential\":{\"openAI_key\":\"<api key>\"},\"actions\":[{\"action_type\":\"PREDICT\",\"method\":\"POST\",\"url\":\"https://${parameters.endpoint}/v1/completions\",\"headers\":{\"Authorization\":\"Bearer ${credential.openAI_key}\"},\"request_body\":\"{ \\\"model\\\": \\\"${parameters.model}\\\", \\\"prompt\\\": \\\"${parameters.prompt}\\\",  \\\"max_tokens\\\": ${parameters.max_tokens},  \\\"temperature\\\": ${parameters.temperature} }\"}],\"client_config\":{\"max_connection\":20,\"connection_timeout\":50000,\"read_timeout\":50000,\"retry_backoff_millis\":200,\"retry_timeout_seconds\":30,\"max_retry_times\":0,\"retry_backoff_policy\":\"constant\"}}]}] and a refresh]"},"status":503}
        at __randomizedtesting.SeedInfo.seed([5A4DB80AB4595406:9ADC268A24B8243E]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:501)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:384)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:374)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:359)
        at app//org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:182)
        at app//org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:155)
        at app//org.opensearch.ml.rest.RestMLRemoteInferenceIT.createConnector(RestMLRemoteInferenceIT.java:841)
        at app//org.opensearch.ml.rest.RestMLRemoteInferenceIT.testDeleteConnector(RestMLRemoteInferenceIT.java:98)
``

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/amistrn), [4](https://github.com/krisfreedain)]

cc: @ylwu-amzn  @varun-lodaya this looks like a problem we should fix soon

**Comment by ylwu-amzn** [comment]
@dhrubo-os Is working on this.

**Comment by dhrubo-os** [comment]
Closing the issue as the PR is merged now.
