### ISSUE TITLE
[BUG] Github actions test causes failure on certain local code -Dtests.locale=az-Cyrl

### ISSUE THREAD

**Issue by brianf-aws** [opensearch-project/ml-commons#2967]
**What is the bug?**
During a [GH action from a commit to a PR](https://github.com/opensearch-project/ml-commons/actions/runs/10908291086/job/30281922405) I had failures I one by one took the reproduction lines [for example](https://github.com/opensearch-project/ml-commons/actions/runs/10908291086/job/30281922405#step:6:2144) Takes you to this command `./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testPrepareRequest" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21` However when you change the `Dtests.locale=az-Cyrl` to `Dtests.locale=hsb ` or `Dtests.locale=en-US ` it ends up passing

**How can one reproduce the bug?**
1. Go to your terminal that has the ml-commons repo for example from main
2. You can run all commands in one sitting or test one by one however All will fail 
```
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testPrepareRequest" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testGetRequest_LocalModelInferenceDisabled" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testGetRequest" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testPrepareBatchRequest" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testGetRequest_RemoteInferenceDisabled" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testGetRequest_LocalModelInferenceDisabled" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testGetRequest" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testPrepareBatchRequest" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.rest.RestMLPredictionActionTests.testGetRequest_RemoteInferenceDisabled" -Dtests.seed=1FD264282B2B1F19 -Dtests.security.manager=false -Dtests.locale=az-Cyrl -Dtests.timezone=Pacific/Tarawa -Druntime.java=21
```
3. Now you can you can see that if you change `az-Cyrl` to (`en-US` or `hsb`) they will all pass

**What is the expected behavior?**
Normally running these gradle commands should result in build succeeded however they all evaluate to failures only when you change them to hsb they will pass. Also github actions should be configured to work with valid local codes or ml-commons should onboard az-Cyrl

**What is your host/environment?**
 - OS: MACOS 14.6.1 
 - OpenSearch Version: 2.16
 - Plugins: ml-commons

**Do you have any screenshots?**
I have a video showing I can forward on request

**Do you have any additional context?**
I was on this commit id when I did the experiment 0d2693180bbd76aab7048490ce9eb4dc5eeb3fe1 Thanks for @b4sjoo Helping debug this problem

**Comment by dbwiddis** [comment]
```java
    public static void main(String[] args) {
        String action = "ml_prediction_action";
        String actionDefault = action.toUpperCase(Locale.ROOT);
        String actionAzerbaijaniCyrillic = action.toUpperCase(Locale.of("az", "AZ", "Cyrl"));
        System.out.println("Does " + actionAzerbaijaniCyrillic + " equal " + actionDefault + "? " + actionAzerbaijaniCyrillic.equals(actionDefault));
    }
```
Output:
> Does ML_PREDİCTİON_ACTİON equal ML_PREDICTION_ACTION? false

Looks like the same dotted-I problem as the Turkish locale.
