### ISSUE TITLE
[FEATURE] Support index.auto_expand_replicas 0-all for .plugins-ml-config

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/ml-commons#3002]
**Is your feature request related to a problem?**
I would like support for `.plugins-ml-config` to be available on all nodes.

**What solution would you like?**
To support the feature, I would like `.plugins-ml-config` index to have the index setting, `index.auto_expand_replicas`, set to `0-all`. This will help with the availability of the index.

**Comment by tronboto** [comment]
Just a heads-up that this change can cause the cluster to go yellow if you have multiple nodes on the same host and `"cluster.routing.allocation.same_shard.host": "true"` is set.
