### ISSUE TITLE
'Invalid Arguments in credential body' on trying to register a new model

### ISSUE THREAD

**Issue by h-tanvi** [opensearch-project/ml-commons#3059]
I am trying to register a new model from together.ai with the _plugins/_ml/models/_register endpoint. I have used https://github.com/opensearch-project/ml-commons/blob/2.x/docs/remote_inference_blueprints/gcp_vertexai_connector_embedding_blueprint.md as a reference, and my request is as follows:

`{
    "name": "Together API Connector",
    "function_name": "remote",
    "model_group_id": "...", // model group id from /_plugins/_ml/model_groups/_register endpoint
    "description": "test togetherai model",
    "connector": {
        "name": "Together API Connector",
        "description": "Test connector to Together API",
        "version": 1,
        "protocol": "http",
        "parameters": {
            "endpoint": "api.together.xyz",
            "model": "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
        },
        "credential": {
            "togetherAI_token": "..." // key added here
        },
        "actions": [
            {
                "action_type": "predict",
                "method": "POST",
                "url": "https://${parameters.endpoint}/v1/chat/completions",
                "headers": {
                    "Authorization": "Bearer ${credential.togetherAI_token}"
                },
                "request_body": "\"{model\": \"${parameters.model}\", \"messages\": ${parameters.messages} }\""
            }
        ]
    }
}`

On calling the service, I keep getting following error with HTTP code 400:
java.lang.IllegalArgumentException: Invalid Arguments in credential body

Please help me understand what is the issue.

**Comment by ylwu-amzn** [comment]
Suggest format the request to make it easier to ready.

**Comment by ylwu-amzn** [comment]
Can you share the complete request without adding comments? Not sure if you are using this `"credential": { "togetherAI_token": "..." // key added here }, ` directly in the request body or not, that's not valid json by adding ` // key added here`

**Comment by ylwu-amzn** [comment]
Tested, this is the correct register model request
```
POST /_plugins/_ml/models/_register
{
    "name": "Together API Connector",
    "function_name": "remote",
    "description": "test togetherai model",
    "model_group_id": "...",
    "connector": {
        "name": "Together API Connector",
        "description": "Test connector to Together API",
        "version": 1,
        "protocol": "http",
        "credential": {
            "togetherAI_token": "..."
        },
        "parameters": {
            "endpoint": "api.together.xyz",
            "model": "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
        },
        "actions": [{
            "action_type": "predict",
            "method": "POST",
            "url": "https://${parameters.endpoint}/v1/chat/completions",
            "headers": {
                "Authorization": "Bearer ${credential.togetherAI_token}"
            },
            "request_body": "{\"model\": \"${parameters.model}\", \"messages\": ${parameters.messages} }"
        }]
    }
}
```
predict
```
POST _plugins/_ml/models/bkXKZ5IBOXlbc3kAJn4C/_predict
{
  "parameters": {
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "hello"
          }
        ]
      }
    ]
  }
}
```

**Comment by h-tanvi** [comment]
Hello @ylwu-amzn , thank you for looking into this, and apologies that I could not get back sooner. I have added the together endpoint to the trusted endpoints using the request body that you have suggested. However, I still see the same error when I try using the /_plugins/_ml/models/_register endpoint with the json request from above message. 

This is the error returned by the endpoint:
`java.lang.IllegalArgumentException: Invalid Arguments in credential body`

**Comment by holdenma** [comment]
@h-tanvi , I have verified the examples I shared before. Can you follow the example exactly ? Reach out to me on Slack if you need more help https://join.slack.com/t/opensearch/shared_invite/zt-2r5scz3ty-5SMPhqJE_Lk2HqC6ex4mWg , join `ml` slack channel, you can find me there.

**Comment by ylwu-amzn** [comment]
@h-tanvi , please follow the example I shared exactly. This is verifed.

**Comment by h-tanvi** [comment]
Hi @ylwu-amzn , thank you for the reply. It seems the issue was only with aos, because AWS was not allowing the credentials to be stored without a secret manager. I have installed opensearch on-premise, and the solution provided by you is working.

**Comment by ylwu-amzn** [comment]
Yes, user must use secret manager and role ARN in AWS managed OpenSearch cluster.

**Comment by Kilowhisky** [comment]
For those who are not sure how to do above: use this tutorial. 

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ml-external-connector.html
