### ISSUE TITLE
Publish plugin zips to maven repo

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/ml-commons#306]
### Description

With existing setup the plugin jars are only published to maven repo, but not the generated plugin zips.

### Related META issue

https://github.com/opensearch-project/opensearch-build/issues/1916

### Current Behavior

Existing all maven publications target the jar files to publish to maven, but not the generated distribution zips.

### Expected Behavior

Along with plugin jars, plugin zips should also be published to maven repo with right maven coordinates, so user can download these plugins using dependancy model.

### Steps To Reproduce

1. Run the gradle assemble task that outputs jar and zips.
2. Using build setup the jars are published to local staging maven repo.
3. Zip's are just added to distribution's folder during build runtime.
4. Finally once build is done, just the jar files are added to local maven repo and updates to the manifest file, but not the zips.

### Proposed solution
A custom gradle plugin solution that can create the publication task for the zips to get published to local staging maven repo with right maven coordinates.
Add/Configure the custom gradle plugin openseearch.pluginzip to the gradle project and test the generated plugin zip's to upload to local maven repo.
More details on how to use the Plugin:
https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip

**Comment by bbarani** [comment]
@sean-zheng-amazon @ylwu-amzn  Can you please make the necessary changes as listed on the document to support publishing your zips to Maven?

**Comment by ylwu-amzn** [comment]
@bbarani sure, should we this ready before 2.0 GA release ?

**Comment by sean-zheng-amazon** [comment]
@ylwu-amzn looks like the team is targetting end of June to have this done. we should start planning the work for upcoming sprint.

**Comment by ylwu-amzn** [comment]
Sure, assigned to Xun @Zhangxunmt

**Comment by Zhangxunmt** [comment]
https://github.com/opensearch-project/ml-commons/pull/343
PR is in review.

**Comment by Zhangxunmt** [comment]
PR merged. Closing the issue.
