### ISSUE TITLE
Update/Delete batch inference tasks that have been idle for a certain time

### ISSUE THREAD

**Issue by rbhavna** [opensearch-project/ml-commons#3161]
In batch inference, we have batch jobs task management by which user can get/cancel the batch jobs running on remote service. Currently, whenever user tries to get a batch job details, we send the request to remote service and update the task status accordingly in ml-commons. Based on the status of such tasks, if there are tasks that are still in running/created status, they will be considered active tasks. We now have a limit on batch inference requests that a user can send based on the running/created tasks in the index. This can be controlled by a setting whose default value is 10 for now.

But the problem is if user does not try explicitly to get the batch job details, the status remains same in ml index even if the status changed on the remote service. Also, these tasks list can grow very large in the long run and we need a mechanism to delete/update the idle tasks that are not being used for a long time. So that we can clean up the index and the limits for batch_inference requests will also be reflected accordingly. 

We can plan on using a sync up job that periodically checks for tasks that are running for a long time and get its actual status from the remote service and update accordingly.

**Comment by dhrubo-os** [comment]
Closing this issue in favor of https://github.com/opensearch-project/ml-commons/issues/3218
