### ISSUE TITLE
[FEATURE] Add LogisticRegression algorithm 

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#318]
Currently we don't have classification algorithms in `ml-commons`. We can start support classification by adding LogisticRegression.

**Comment by Zhangxunmt** [comment]
What are you proposing?
What problems are you trying to solve?
What is the user experience going to be?
Why should it be built? Any reason not to?
What will it take to execute?
What are remaining open questions?

**Comment by elfisher** [comment]
This looks exciting! Thanks for putting the proposal together @Zhangxunmt! Could we add API examples of how someone would use this (PPL and REST)?

**Comment by alexahorgan** [comment]
Feature Review Feedback 7/21/22:
Add API examples and identify a way to sort the list of algorithms into categories (naming conventions).

**Comment by Zhangxunmt** [comment]
API Example: 
Train a Logistic Regression Model using the API in Ml-Common Plugin. 

POST _plugins/_ml/_train/logistic_regression
{
  "parameters": {
    "target": "class"
  },
  "input_query": {
    "query": {
      "match_all": {}
    },
    "_source": [
      "sepal_length_in_cm",
      "sepal_width_in_cm",
      "petal_length_in_cm",
      "petal_width_in_cm",
      "class"
    ],
    "size": 200
  },
  "input_index": [
    "iris_data"
  ]
}

Predict result for the trained Logistic Regression Model using the API in Ml-Common Plugin.
POST _plugins/_ml/_predict/logistic_regression/bMjQYYIBaEQ9YIwg1Bx3
{
  "parameters": {
    "target": "class"
  },
  "input_data": {
    "column_metas": [
      {
        "name": "sepal_length_in_cm",
        "column_type": "DOUBLE"
      },
      {
        "name": "sepal_width_in_cm",
        "column_type": "DOUBLE"
      },
      {
        "name": "petal_length_in_cm",
        "column_type": "DOUBLE"
      },
      {
        "name": "petal_width_in_cm",
        "column_type": "DOUBLE"
      }
    ],
    "rows": [
      {
        "values": [
          {
            "column_type": "DOUBLE",
            "value": 5.3
          },
          {
            "column_type": "DOUBLE",
            "value": 3.7
          },
          {
            "column_type": "DOUBLE",
            "value": 1.5
          },
          {
            "column_type": "DOUBLE",
            "value": 0.2
          }
        ]
      }
    ]
  }
}

Prediction Result:
{
  "status" : "COMPLETED",
  "prediction_result" : {
    "column_metas" : [
      {
        "name" : "result",
        "column_type" : "STRING"
      }
    ],
    "rows" : [
      {
        "values" : [
          {
            "column_type" : "STRING",
            "value" : "Iris-setosa"
          }
        ]
      }
    ]
  }
}

**Comment by alexahorgan** [comment]
Demo Session Feedback (8/3/22)

**Outcome:**
Approved, ship it. 

**Action Items:**
Consider incorporating names for model IDs.
