### ISSUE TITLE
[BUG] MLInferenceIngestProcessor has xContentRegistry as null 

### ISSUE THREAD

**Issue by brianf-aws** [opensearch-project/ml-commons#3276]
**What is the bug?**
[Commit that introduces local models to MLInferenceIngestProcessor](https://github.com/opensearch-project/ml-commons/commit/7cd52915d04d8ac7ddb6e37a74a256603587ce69#diff-5fb7a6291568399efed0b4be65f70e91206634d3a1e5d1265243f1c204c0d81fR1011)

On creation of the Ingest processor the MLInferenceIngestProcessor has no valid [xContentRegistry](https://github.com/opensearch-project/ml-commons/blob/7cd52915d04d8ac7ddb6e37a74a256603587ce69/plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java#L1011) which is used to create valid [MLInput](https://github.com/opensearch-project/ml-commons/blob/684627ac57f73c47e772d0cd9710932c3326bd39/common/src/main/java/org/opensearch/ml/common/input/MLInput.java#L233-L238) objects used for model prediction 

Contrast this with the [MLInferenceSearchResponseProcessor](https://github.com/opensearch-project/ml-commons/blob/c2a40c195402827fc5f113b865c12701f76fa60a/plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java#L1035) That has a valid contentRegistry, this processor is able to correctly make objects and can produce valid model input.

If you want to test this locally I reccomend you [follow the steps](https://github.com/opensearch-project/ml-commons/pull/3258) to create a local embedding 

Then run the following 

```
PUT {{ _.domain }}/_ingest/pipeline/asymmetric_embedding_ingest_pipeline
{
	"description": "ingest passage text and generate a embedding using an asymmetric model",
	"processors": [
        {
	        "ml_inference": {
        
		        "model_input": "{\"text_docs\":[\"${input_map.text_docs}\"],\"target_response\":[\"sentence_embedding\"],\"parameters\":{\"content_type\":\"query\"}}",
		        "function_name": "text_embedding",
		        "model_id": "{{ _.model_id }}",
		        "input_map": [
			        {
				        "text_docs": "description"
			        }
		        ],
		        "output_map": [
			        {
				        "fact_embedding": "$.inference_results.*.output.*.data",
				        "embedding_size": "$.inference_results.*.output.*.shape[0]"
			        }
		        ]
	        }
        }
	]
}


### -------------------------- ack expected 
POST {{ _.domain }}/_ingest/pipeline/asymmetric_embedding_ingest_pipeline/_simulate
{
	"docs": [
          {
	          "_index": "my-index",
	          "_id": "1",
	          "_source": {
		          "title": "Central Park",
		          "description": "A large public park in the heart of New York City, offering a wide range of recreational activities.",
		          "content_type": "passage"
	          }
          }
	]
}
```

**What is the expected behavior?**
A proper embedding should appear as a result of the simulating the ingest pipeline.

**What is your host/environment?**
 - OS: 2.18
 - Plugins

**Comment by brianf-aws** [comment]
After investigating, I realized that this requires a open-search core code change along with a minor Ml-Commons change. More specifically, it requires that the [IngestService class](https://github.com/opensearch-project/OpenSearch/blob/35c366ddc794e0600184cf406c06ae65061e28ce/server/src/main/java/org/opensearch/node/Node.java#L937) change its constructor to have a content registry object as a new parameter. 
This will obviously cause a cascading amount of changes related to ingest service. However, this sort of code change was done previously as shown [here](https://github.com/opensearch-project/OpenSearch/commit/c0c76e6db6b6a39401700de54f7aa64e2cc6f9f1) which will pass indiceServices to ingest processors by modifying the node class.

https://github.com/opensearch-project/ml-commons/blob/9a4166ed91f7682a4c80def65ca6b44944ef5e64/plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java#L1068

This is the most sensible solution as any new ingest processor can benefit from making objects using the xContentRegistry provided by the Node class. This also benefits the MlInferenceIngest processor to create custom ML Inputs based on any new model that comes up as shown by the [Asymmetric Model Type ](https://github.com/opensearch-project/ml-commons/pull/2123).

## Are there any easier ways to solve this issue?


Currently we can not circumvent this by using the createComponents method within MLPlugin
https://github.com/opensearch-project/ml-commons/blob/9a4166ed91f7682a4c80def65ca6b44944ef5e64/plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java#L458-L470
as the creation of the  ingestProcessor gets called before the createComponents method 
https://github.com/opensearch-project/ml-commons/blob/9a4166ed91f7682a4c80def65ca6b44944ef5e64/plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java#L1063



One way to easily remove the need for the code change is to change the order of creation with the node class. But this is a terrible idea  as we will depend on the order of code to make sure everything is correct see below.

This is the order the code executes which explains why the xContentRegistry is null when creating the ingest processor
1. [IngestService](https://github.com/opensearch-project/OpenSearch/blob/35c366ddc794e0600184cf406c06ae65061e28ce/server/src/main/java/org/opensearch/node/Node.java#L937-L946) gets invoked (first )calling the factories of the processors this includes the MlInferenceIngestProcessor at which time in point the xContentRegistry is null 
2. [The plugins load their configurations](https://github.com/opensearch-project/OpenSearch/blob/35c366ddc794e0600184cf406c06ae65061e28ce/server/src/main/java/org/opensearch/node/Node.java#L985-L1002) (more specifically the MLPlugin), which service the xContentRegistry therefore the processor doesnt have the valid object in time.

**Comment by austintlee** [comment]
I think you should start with a PR in core and get feedback.  Just to be clear, you want to introduce a new `xContentRegistry` member in org.opensearch.ingest.Processor.Parameters class, right?  That's exactly what SearchPipeline is doing.

**Comment by brianf-aws** [comment]
Hey Austin! @austintlee, Yes thats part of it; this involves several code changes
1. IngestService has a xContentRegistry paramater
2. Give [Ingest Processor Parameters](https://github.com/opensearch-project/OpenSearch/blob/1219c568248fafa479d67a1eaa6e3e2d9748701e/server/src/main/java/org/opensearch/ingest/Processor.java#L161) a new xContentRegistry field, you might get mixed up since the Search pipeline has a same class name but it has the xContentRegistry which is why its able to work
3. Now within the MLPlugins class we do the following (what you suggested)
https://github.com/opensearch-project/ml-commons/blob/9a4166ed91f7682a4c80def65ca6b44944ef5e64/plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java#L1068
```java
 new MLInferenceIngestProcessor.Factory(parameters.scriptService, parameters.client, paramters.xContentRegistry) 
```

**Comment by brianf-aws** [comment]
Currently since implementation of ingestProcessors have a null content registry we can force the **xContentRegistry** to have the registry as specified by the getNamedXContent() method
https://github.com/opensearch-project/ml-commons/blob/9a4166ed91f7682a4c80def65ca6b44944ef5e64/plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java#L912

this is a temporary ML-Commons unblocker for using local models but I would need to have a OpenSearch core fix which would take awhile.

Here is the plan of action to make this happen. Within the specified order.
- [X] ML-Commons Temporary unblocker for parametrized local models to be used for MLInferenceIngest Processor : https://github.com/opensearch-project/ml-commons/pull/3281
- [ ] OpenSearch Core change : [PR to be shared]
- [ ] ML-Commons change with contentRegistry coming from core. : [PR to be shared]
