### ISSUE TITLE
[FEATURE] Adding RCFSummarize clustering 

### ISSUE THREAD

**Issue by model-collapse** [opensearch-project/ml-commons#356]
**What?** 
RCFSummarize is a clustering algorithm inspired by CURE. We can offer one more choice to our users on clustering algorith,

**Why?**
Different with K-Means, this algorithm do not require a fixed K indicating the actual number of categories, instead it can adaptively find out the real K. This is very meaningful that people can obtain more accurate clustering performance with lower barrier.

**How?**
The RCF (random cut forest) library already consists the implementation of RCFSummarize, thus we will add a function to ml-commons and adapt the interface with RCF library.

**Comment by ylwu-amzn** [comment]
Suggest follow this feature template https://github.com/opensearch-project/.github/blob/main/.github/ISSUE_TEMPLATE/PROPOSAL_TEMPLATE.md

**Comment by sean-zheng-amazon** [comment]
This has been released with 2.2, closing
