### ISSUE TITLE
[FEATURE][NLP] Add an ingest processor to support document embeddings ingestion

### ISSUE THREAD

**Issue by jngz-es** [opensearch-project/ml-commons#364]
### What are we building?

User can define a pipeline with this ingest processor and attach the pipeline when ingesting the documents. The processor applies a NLP model like transformer to the documents and appends an embedding field for each document.

### Why are we building it? 

With this processor, each document has an embedding presentation which allows us to improve OpenSearch customer experience like semantic search etc. through introducing some NLP features.

**Comment by jmazanec15** [comment]
@jngz-es What is the connection with this for search? Would common functionality be able to be used in a search processor, similar to this [Geo](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/query/VectorGeoShapeQueryProcessor.java) one?

**Comment by ylwu-amzn** [comment]
Fixed in https://github.com/opensearch-project/neural-search/issues/19
