### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/ml-commons#366]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @sean-zheng-amazon @ylwu-amzn can you please post an update and make the necessary changes to align with core branching strategy?
Thank you
@dblock @bbarani @CEHENKLE

**Comment by ylwu-amzn** [comment]
Thanks @prudhvigodithi, I think this branching strategy is good and ml-commons is following this strategy.

**Comment by ps48** [comment]
@ylwu-amzn @prudhvigodithi SQL main branch PR is waiting ml-commons main to be bumped to 3.0.

**Comment by ylwu-amzn** [comment]
Thanks, @rbhavna is working on bumping main branch to 3.0

**Comment by dblock** [comment]
There should be nothing blocking this rn. To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3
