### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/ml-commons#415]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases. 
Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

**Comment by b4sjoo** [comment]
This issue is resolved by PR #681
