### ISSUE TITLE
ml-commons admin panel OSD Plugin 

### ISSUE THREAD

**Issue by model-collapse** [opensearch-project/ml-commons#427]
ml-common is good machine learning library plugin for OpenSearch which enables the users to train their machine learning models using the data inside OpenSearch storage and conduct inference using the trained models. However, at this moment, people can only do these things by calling API. According to practices of AI model training, visualization will bring much better experience and boost the model development efficiency. Thus we propose to develop a web-based model training UI for ml-commons as its administration panel, where people can set up the training conditions and conduct the training online, evaluating them with dataset afterward as well. As a matter of course, we also need some UIs to manage the model we have trained, e.g. to filter the qualified models or to delete models that will never be used.

**Comment by ylwu-amzn** [comment]
Already released.
