### ISSUE TITLE
Forward port changes in 2.x to main branch

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#553]
`main` branch bumped to 3.0 which has some breaking changes. So we decided to develop features on `2.x` branch for 2.4 release to save effort of fixing breaking changes in main branch. 
Now we need to forward port changes in `2.x` branch to `main` branch.

**Comment by b4sjoo** [comment]
All code commits in branch 2.x were merged at this time. Now wait for infra team to publish maven build for our latest ml-commons version.
