### ISSUE TITLE
[FEATURE] Support GPU servers for model serving framework

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#576]
We released model serving framework in 2.4 as experimental feature ([doc link](https://opensearch.org/docs/latest/ml-commons-plugin/model-serving-framework/)). In 2.4, we have limited support running pytorch model on GPU ML nodes.

In 2.5, we plan to support popular GPU instances:
1. NVIDIA GPU
2. AWS Inferentia Instance

**Comment by b4sjoo** [comment]
We have added a doc to guide user how to prepare GPU ML node to run model serving framework in regards of this issue #677, so we think we can close it.
