### ISSUE TITLE
Backport Windows support to 1.x branch

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/ml-commons#579]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/181, backport Windows support to 1.x branch.

- [ ] Passing CI for 1.x branch on Windows
- [ ] Documentation

If you are already have an issue tracking backport Windows CI to 1.x branch, please link here.

**Comment by sean-zheng-amazon** [comment]
code merged, closing
