### ISSUE TITLE
[FEATURE] enhance profile API to return model deployment info

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/ml-commons#646]
**Is your feature request related to a problem?**
The current ML profile API doesn't return model deployment status information, user is not able to check the model running status on each ml node. The feature request is to return the model deployment status information in profile API.

**What solution would you like?**
Adding a new path parameter `profile_and_deployment` which has three different values: `profile`, `deployment` and `all` to represent which information to return. When the parameter value is `deployment` or `all`, returning model deployment info under a new entry name: `models`. 

**What alternatives have you considered?**
Creating a new API for this feature is another solution, but the most codes will be duplicated, so merging them together.

**Do you have any additional context?**
NA

**Comment by gaiksaya** [comment]
Hi @opensearch-project/machine-learning 
This issue was tagged for 2.6.0. Can you close it if it was resolved or tag is to be tracked for next iteration?
Thanks!
