### ISSUE TITLE
[FEATURE] Add circuit breaker for native memory usage

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#648]
**Is your feature request related to a problem?**
When load model, it will consume native memory. If all native memory used, operating system will kill OpenSearch automatically. 

**What solution would you like?**
We should build circuit breaker for native memory usage just like the JVM heap circuit breaker. If native memory usage exceeds some threshold, we will throw exception

**What alternatives have you considered?**
no

**Do you have any additional context?**
OsService class provides operation system memory usage. We can use that to build a circuit breaker.

**Comment by b4sjoo** [comment]
Feature PR merged, we can close this.
