### ISSUE TITLE
[FEATURE] Update model API

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#666]
We don't have update model API. After user trained a model or uploaded a model, they have no way to modify the model doc.

Some part of the model can't be updated like the model type, hyper parameters etc. 
Some part can be updated like: description and model name.

We should figure out which part is mutable and create update model API.

**Comment by lauralexis** [comment]
1. When editing a **model group**, what fields are editable?
    1. name
    2. description
    3. tag keys (can be deleted or added)
    4. tag key value type (string or number)


2. When editing a **model version**, what fields are editable?
    1. artifact file/url
    2. model file format
    3. JSON configuration
    5. add a tag key to the version that has been predefined for the model group; edit a tag value; remove a tag key from the version
    7. version notes

**Comment by dhrubo-os** [comment]
Update model api is released in 2.12.0. Closing this issue.
