### ISSUE TITLE
Support training KMeans with Oracle Tribuo library

### ISSUE THREAD

**Issue by spbjss** [opensearch-project/ml-commons#67]
**Is your feature request related to a problem? Please describe.**
The training/predict through Oracle Tribuo library will fail because of this error with JVM 11, 14 and 15.
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")

Tribuo library only works with JVM 8.

**Describe the solution you'd like**
training and prediction should support JVM 11, 14, 15.

**Comment by ylwu-amzn** [comment]
Create an issue to discuss whether it's possible to remove "modifyThreadGroup" checking in `SecureSM`
https://github.com/opensearch-project/OpenSearch/issues/1649
