### ISSUE TITLE
[FEATURE] Clarity on framework types for text embedding models

### ISSUE THREAD

**Issue by bsowell** [opensearch-project/ml-commons#723]
This may be more of a documentation issue, but it would be very helpful to get some clarity on how text embedding models are prepared for use in OpenSearch. For example, the all-MiniLM-L6-v2 model is included several times in the tests, including two different versions of TorchScript, [one of which](https://github.com/opensearch-project/ml-commons/blob/a08e4825db916c7138a28f3dd259732d6ba8decd/ml-algorithms/src/test/resources/org/opensearch/ml/engine/algorithms/text_embedding/all-MiniLM-L6-v2_torchscript_sentence-transformer.zip) appears to use the sentence_transformers framework_type, and [one](https://github.com/opensearch-project/ml-commons/blob/a08e4825db916c7138a28f3dd259732d6ba8decd/ml-algorithms/src/test/resources/org/opensearch/ml/engine/algorithms/text_embedding/all-MiniLM-L6-v2_torchscript_huggingface.zip) that uses the huggingface_transforms type. Are these equivalent? Are they prepared differently, and is there a reason we would favor one over the other? 

In general the documentation on how to convert HuggingFace models to TorchScript is fairly poor (not OpenSearch specific), and it would be amazing if you were able to share the scripts you used to generate the models present in the tests, either in the documentation or somewhere in the repo.

**Comment by bsowell** [comment]
After looking through some issues, I found references to the appropriate methods in opensearch-py-ml: 

- https://github.com/opensearch-project/ml-commons/blob/2.x/docs/model_serving_framework/text_embedding_model_examples.md
- https://opensearch-project.github.io/opensearch-py-ml/reference/api/sentence_transformer.save_as_pt.html
- https://github.com/opensearch-project/opensearch-py-ml/blob/main/opensearch_py_ml/ml_models/sentencetransformermodel.py#L687

It would be helpful to link these from the docs, but this at least addresses my immediate questions. Thanks!

**Comment by ylwu-amzn** [comment]
@bsowell Thanks a lot. This is a good suggestion. Will add/link more docs. We are improving this feature to make it GA ready. Welcome for any feedback/suggestions!

**Comment by ylwu-amzn** [comment]
And this blog is a good example for how to use neural search with ml-commons https://opensearch.org/blog/similar-document-search/

**Comment by bsowell** [comment]
Thanks. I had specifically been stuck when trying to use a model other than `all-MiniLM-L6-v2` (which is already included in the right format in the OpenSearch test resources). The `save_as_pt` method seems to be what I am looking for. Thanks for the references!

**Comment by ylwu-amzn** [comment]
@bsowell Cool. Feel free to cut issues if you see more issues.

If you have requirements for new model types/use cases, please don't hesitate to cut a feature request via Github issue. We will be glad to support your use cases!
