### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/ml-commons#727]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by ylwu-amzn** [comment]
@dblock Do we have any doc explaining the definition of maintainers and codeowners, and their difference?

**Comment by dblock** [comment]
CODEOWNERS = https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
MAINTAINERS = people with "Maintain" level permissions

Feel free to contribute links to .github, I think we didn't spell that out.

**Comment by ylwu-amzn** [comment]
Thanks @dblock , we don't have permission to edit that.  @bbarani helped remove extra teams/guys and add the correct maintainers, Thanks @bbarani.

I will close this issue now. Feel free to reopen if you see more issues.

**Comment by dblock** [comment]
Verified actual permissions, thanks.
