### ISSUE TITLE
[FEATURE] Support uploading pre-trained model from model repo

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#745]
**Is your feature request related to a problem?**
User can use upload model API to upload their own model. But they need to prepare a traced model first (we support torchscript or ONNX). We have published some Huggingface pre-trained models to OpenSearch model repo. With that, we can enhance upload API to simply upload model from model repo.

**What solution would you like?**
User only need to provide model name, version and format when upload model from model repo.

```
POST /_plugins/_ml/models/_upload
{
  "name": "huggingface/sentence-transformers/all-MiniLM-L12-v2",
  "version": "1.0.1",
  "model_format": "TORCH_SCRIPT"
}
```

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
No

**Comment by gaiksaya** [comment]
Hi @opensearch-project/machine-learning 
This issue was tagged for 2.6.0. 
Can you close it if it was resolved or tag is to be tracked for next iteration?
Thanks!
