### ISSUE TITLE
[FEATURE] Remote Inference in Ml-commons

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/ml-commons#746]
**Is your feature request related to a problem?**
In addition to build-in ML models and customer uploaded models, Ml-common needs to extend the ML Model Serving Framework to allow customers to use their choice of ML tech like OpenAI, Amazon SageMaker Hosting, Tensorflow Serving and NVIDIA’s Triton Inference Server, etc. Additionally, it empowers developers/contributors and partners with a simple way to build and distribute integrations in the OpenSearch community. 

**What solution would you like?**
Ml-commons will build a framework that 1) provide a generic remote ML-model server template that developers can use to provision connections to remote servers; and 2) enables no-code integrations through web services to run ML workloads outside of OpenSearch Cluster, and 3) provides Rest APIs to manage remote models.

**Comment by ylwu-amzn** [comment]
Released in 2.9 https://opensearch.org/docs/latest/ml-commons-plugin/extensibility/index/
