### ISSUE TITLE
Publish ml-common Client jars to maven

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/ml-commons#763]
As the central build workflow has disabled publishing artifacts to maven, each repo needs to publish maven snapshots. ML-common has finished this task in #734 . However, the ml-client jars are not included. SQL and Neural plugin depends on the ml-common clients jar downloaded from maven, so we need to add a step in mavan-publish workflow to publish client jars to maven.

**Comment by Zhangxunmt** [comment]
@MaxKsyunz, @Yury-Fridlyand , can you confirm you are resolving this issue?

**Comment by Yury-Fridlyand** [comment]
I'm working on this.
