### ISSUE TITLE
[BUG] Fix Security Check in Github workflow

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/ml-commons#788]
**What is the bug?**
The Mend Security Check and security report in the workflow for each PR always give wrong warnings. e.g. https://github.com/opensearch-project/ml-commons/pull/760/checks?check_run_id=11702221277. We need to look into this issue and fix the security check workflow.

**Comment by b4sjoo** [comment]
Closed this issue due to it's core side dependency. If this keeps occurring we can look again.
