### ISSUE TITLE
[BUG]Names don't adhere to plugin naming convention

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/ml-commons#847]
**What is the bug?**
Align all names to the convention:
https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#opensearch-plugins

We should adjust the folder and move build.gradle, etc. to the root folder of the repo.

[opensearchplugin metadata is missing from build.gradle](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#metadata)

**Do you have any additional context?**
Referred to here:
https://github.com/opensearch-project/opensearch-plugins/issues/174

**Comment by ylwu-amzn** [comment]
You can find plugin name here https://github.com/opensearch-project/ml-commons/blob/main/plugin/build.gradle#L39

I think we are following the naming convention
