### ISSUE TITLE
[BUG] ONNX GPU runtime can't work on CPU aarch64 server

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#848]
**What is the bug?**
Tried ONNX model on aarch64 CPU server, it will throw such error.
Don't see this issue on x86 CPU server. I guess that's because some ONNX runtime native library not ready on aarch64 CPU server.

```
no onnxruntime in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
```

**How can one reproduce the bug?**
1. Download OS tarball and install it on aarch64 CPU server
2. Upload a model 
3. Load model, then check the task, can see it failed

**What is the expected behavior?**
Change this line `implementation "com.microsoft.onnxruntime:onnxruntime_gpu:1.13.1"` to `implementation "com.microsoft.onnxruntime:onnxruntime:1.13.1"`, Build a new plugin zip and reinstall , then can see ONNX model loaded successfully.

**Do you have any additional context?**
Add any other context about the problem.

**Comment by b4sjoo** [comment]
This problem is fixed on AOS through disabling GPU runtime on AOS.
